// ------------------------------
// License(s)
//
// Copyright 2024 Aldrin Montana
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// ------------------------------
// Dependencies

#include "mohair.hpp"


// ------------------------------
// Functions

namespace mohair::extensions {

  // >> Helper functions for generated code
  SubstraitFunctionExt* RegisterFunctionExtension(string extension_uri) {
    const auto& ext_entry = mohair::fn_extensions.find(extension_uri);
    if (ext_entry != mohair::fn_extensions.end()) { return nullptr; }

    auto& inserted_entry = mohair::fn_extensions[extension_uri];
    inserted_entry       = std::make_unique<SubstraitFunctionExt>(extension_uri);

    return inserted_entry.get();
  }

  // >> Generated code
  bool RegisterFunctionExtensions() {
    SubstraitFunctionExt* new_ext0 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_datetime.yaml");
    new_ext0->AddFunction("extract", { "timestamp_tz", "string" }, "i64");
    new_ext0->AddFunction("extract", { "precision_timestamp_tz", "string" }, "i64");
    new_ext0->AddFunction("extract", { "timestamp" }, "i64");
    new_ext0->AddFunction("extract", { "precision_timestamp" }, "i64");
    new_ext0->AddFunction("extract", { "date" }, "i64");
    new_ext0->AddFunction("extract", { "time" }, "i64");
    new_ext0->AddFunction("extract", { "timestamp_tz", "string" }, "i64");
    new_ext0->AddFunction("extract", { "precision_timestamp_tz", "string" }, "i64");
    new_ext0->AddFunction("extract", { "timestamp" }, "i64");
    new_ext0->AddFunction("extract", { "precision_timestamp" }, "i64");
    new_ext0->AddFunction("extract", { "date" }, "i64");
    new_ext0->AddFunction("extract_boolean", { "timestamp" }, "boolean");
    new_ext0->AddFunction("extract_boolean", { "precision_timestamp" }, "boolean");
    new_ext0->AddFunction("extract_boolean", { "timestamp_tz", "string" }, "boolean");
    new_ext0->AddFunction("extract_boolean", { "precision_timestamp_tz", "string" }, "boolean");
    new_ext0->AddFunction("extract_boolean", { "date" }, "boolean");
    new_ext0->AddFunction("add", { "timestamp", "interval_year" }, "timestamp");
    new_ext0->AddFunction("add", { "precision_timestamp", "interval_year" }, "precision_timestamp");
    new_ext0->AddFunction("add", { "timestamp_tz", "interval_year", "string" }, "timestamp_tz");
    new_ext0->AddFunction("add", { "precision_timestamp_tz", "interval_year", "string" }, "precision_timestamp_tz");
    new_ext0->AddFunction("add", { "date", "interval_year" }, "timestamp");
    new_ext0->AddFunction("add", { "timestamp", "interval_day" }, "timestamp");
    new_ext0->AddFunction("add", { "precision_timestamp", "interval_day" }, "precision_timestamp");
    new_ext0->AddFunction("add", { "timestamp_tz", "interval_day" }, "timestamp_tz");
    new_ext0->AddFunction("add", { "precision_timestamp_tz", "interval_day" }, "precision_timestamp_tz");
    new_ext0->AddFunction("add", { "date", "interval_day" }, "timestamp");
    new_ext0->AddFunction("multiply", { "i8", "interval_day" }, "interval_day");
    new_ext0->AddFunction("multiply", { "i16", "interval_day" }, "interval_day");
    new_ext0->AddFunction("multiply", { "i32", "interval_day" }, "interval_day");
    new_ext0->AddFunction("multiply", { "i64", "interval_day" }, "interval_day");
    new_ext0->AddFunction("multiply", { "i8", "interval_year" }, "interval_year");
    new_ext0->AddFunction("multiply", { "i16", "interval_year" }, "interval_year");
    new_ext0->AddFunction("multiply", { "i32", "interval_year" }, "interval_year");
    new_ext0->AddFunction("multiply", { "i64", "interval_year" }, "interval_year");
    new_ext0->AddFunction("add_intervals", { "interval_day", "interval_day" }, "interval_day");
    new_ext0->AddFunction("add_intervals", { "interval_year", "interval_year" }, "interval_year");
    new_ext0->AddFunction("subtract", { "timestamp", "interval_year" }, "timestamp");
    new_ext0->AddFunction("subtract", { "precision_timestamp", "interval_year" }, "precision_timestamp");
    new_ext0->AddFunction("subtract", { "timestamp_tz", "interval_year" }, "timestamp_tz");
    new_ext0->AddFunction("subtract", { "precision_timestamp_tz", "interval_year" }, "precision_timestamp_tz");
    new_ext0->AddFunction("subtract", { "timestamp_tz", "interval_year", "string" }, "timestamp_tz");
    new_ext0->AddFunction("subtract", { "precision_timestamp_tz", "interval_year", "string" }, "precision_timestamp_tz");
    new_ext0->AddFunction("subtract", { "date", "interval_year" }, "date");
    new_ext0->AddFunction("subtract", { "timestamp", "interval_day" }, "timestamp");
    new_ext0->AddFunction("subtract", { "precision_timestamp", "interval_day" }, "precision_timestamp");
    new_ext0->AddFunction("subtract", { "timestamp_tz", "interval_day" }, "timestamp_tz");
    new_ext0->AddFunction("subtract", { "precision_timestamp_tz", "interval_day" }, "precision_timestamp_tz");
    new_ext0->AddFunction("subtract", { "date", "interval_day" }, "date");
    new_ext0->AddFunction("lte", { "timestamp", "timestamp" }, "boolean");
    new_ext0->AddFunction("lte", { "precision_timestamp", "precision_timestamp" }, "boolean");
    new_ext0->AddFunction("lte", { "timestamp_tz", "timestamp_tz" }, "boolean");
    new_ext0->AddFunction("lte", { "precision_timestamp_tz", "precision_timestamp_tz" }, "boolean");
    new_ext0->AddFunction("lte", { "date", "date" }, "boolean");
    new_ext0->AddFunction("lte", { "interval_day", "interval_day" }, "boolean");
    new_ext0->AddFunction("lte", { "interval_year", "interval_year" }, "boolean");
    new_ext0->AddFunction("lt", { "timestamp", "timestamp" }, "boolean");
    new_ext0->AddFunction("lt", { "precision_timestamp", "precision_timestamp" }, "boolean");
    new_ext0->AddFunction("lt", { "timestamp_tz", "timestamp_tz" }, "boolean");
    new_ext0->AddFunction("lt", { "precision_timestamp_tz", "precision_timestamp_tz" }, "boolean");
    new_ext0->AddFunction("lt", { "date", "date" }, "boolean");
    new_ext0->AddFunction("lt", { "interval_day", "interval_day" }, "boolean");
    new_ext0->AddFunction("lt", { "interval_year", "interval_year" }, "boolean");
    new_ext0->AddFunction("gte", { "timestamp", "timestamp" }, "boolean");
    new_ext0->AddFunction("gte", { "precision_timestamp", "precision_timestamp" }, "boolean");
    new_ext0->AddFunction("gte", { "timestamp_tz", "timestamp_tz" }, "boolean");
    new_ext0->AddFunction("gte", { "precision_timestamp_tz", "precision_timestamp_tz" }, "boolean");
    new_ext0->AddFunction("gte", { "date", "date" }, "boolean");
    new_ext0->AddFunction("gte", { "interval_day", "interval_day" }, "boolean");
    new_ext0->AddFunction("gte", { "interval_year", "interval_year" }, "boolean");
    new_ext0->AddFunction("gt", { "timestamp", "timestamp" }, "boolean");
    new_ext0->AddFunction("gt", { "precision_timestamp", "precision_timestamp" }, "boolean");
    new_ext0->AddFunction("gt", { "timestamp_tz", "timestamp_tz" }, "boolean");
    new_ext0->AddFunction("gt", { "precision_timestamp_tz", "precision_timestamp_tz" }, "boolean");
    new_ext0->AddFunction("gt", { "date", "date" }, "boolean");
    new_ext0->AddFunction("gt", { "interval_day", "interval_day" }, "boolean");
    new_ext0->AddFunction("gt", { "interval_year", "interval_year" }, "boolean");
    new_ext0->AddFunction("assume_timezone", { "timestamp", "string" }, "timestamp_tz");
    new_ext0->AddFunction("assume_timezone", { "precision_timestamp", "string" }, "precision_timestamp_tz");
    new_ext0->AddFunction("assume_timezone", { "date", "string" }, "timestamp_tz");
    new_ext0->AddFunction("local_timestamp", { "timestamp_tz", "string" }, "timestamp");
    new_ext0->AddFunction("local_timestamp", { "precision_timestamp_tz", "string" }, "precision_timestamp");
    new_ext0->AddFunction("strptime_time", { "string", "string" }, "time");
    new_ext0->AddFunction("strptime_date", { "string", "string" }, "date");
    new_ext0->AddFunction("strptime_timestamp", { "string", "string", "string" }, "timestamp_tz");
    new_ext0->AddFunction("strptime_timestamp", { "string", "string" }, "timestamp_tz");
    new_ext0->AddFunction("strftime", { "timestamp", "string" }, "string");
    new_ext0->AddFunction("strftime", { "precision_timestamp", "string" }, "string");
    new_ext0->AddFunction("strftime", { "timestamp_tz", "string", "string" }, "string");
    new_ext0->AddFunction("strftime", { "precision_timestamp_tz", "string", "string" }, "string");
    new_ext0->AddFunction("strftime", { "date", "string" }, "string");
    new_ext0->AddFunction("strftime", { "time", "string" }, "string");
    new_ext0->AddFunction("round_temporal", { "timestamp", "i64", "timestamp" }, "timestamp");
    new_ext0->AddFunction("round_temporal", { "precision_timestamp", "i64", "precision_timestamp" }, "precision_timestamp");
    new_ext0->AddFunction("round_temporal", { "timestamp_tz", "i64", "string", "timestamp_tz" }, "timestamp_tz");
    new_ext0->AddFunction("round_temporal", { "precision_timestamp_tz", "i64", "string", "precision_timestamp_tz" }, "precision_timestamp_tz");
    new_ext0->AddFunction("round_temporal", { "date", "i64", "date" }, "date");
    new_ext0->AddFunction("round_temporal", { "time", "i64", "time" }, "time");
    new_ext0->AddFunction("round_calendar", { "timestamp", "i64" }, "timestamp");
    new_ext0->AddFunction("round_calendar", { "precision_timestamp", "i64" }, "precision_timestamp");
    new_ext0->AddFunction("round_calendar", { "timestamp_tz", "i64", "string" }, "timestamp_tz");
    new_ext0->AddFunction("round_calendar", { "precision_timestamp_tz", "i64", "string" }, "precision_timestamp_tz");
    new_ext0->AddFunction("round_calendar", { "date", "i64", "date" }, "date");
    new_ext0->AddFunction("round_calendar", { "time", "i64", "time" }, "time");
    new_ext0->AddFunction("min", { "date" }, "date");
    new_ext0->AddFunction("min", { "time" }, "time");
    new_ext0->AddFunction("min", { "timestamp" }, "timestamp");
    new_ext0->AddFunction("min", { "precision_timestamp" }, "precision_timestamp");
    new_ext0->AddFunction("min", { "timestamp_tz" }, "timestamp_tz");
    new_ext0->AddFunction("min", { "precision_timestamp_tz" }, "precision_timestamp_tz");
    new_ext0->AddFunction("min", { "interval_day" }, "interval_day");
    new_ext0->AddFunction("min", { "interval_year" }, "interval_year");
    new_ext0->AddFunction("max", { "date" }, "date");
    new_ext0->AddFunction("max", { "time" }, "time");
    new_ext0->AddFunction("max", { "timestamp" }, "timestamp");
    new_ext0->AddFunction("max", { "timestamp_tz" }, "timestamp_tz");
    new_ext0->AddFunction("max", { "precision_timestamp_tz" }, "precision_timestamp_tz");
    new_ext0->AddFunction("max", { "interval_day" }, "interval_day");
    new_ext0->AddFunction("max", { "interval_year" }, "interval_year");

    SubstraitFunctionExt* new_ext1 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_comparison.yaml");
    new_ext1->AddFunction("not_equal", { "any1", "any1" }, "boolean");
    new_ext1->AddFunction("equal", { "any1", "any1" }, "boolean");
    new_ext1->AddFunction("is_not_distinct_from", { "any1", "any1" }, "boolean");
    new_ext1->AddFunction("is_distinct_from", { "any1", "any1" }, "boolean");
    new_ext1->AddFunction("lt", { "any1", "any1" }, "boolean");
    new_ext1->AddFunction("gt", { "any1", "any1" }, "boolean");
    new_ext1->AddFunction("lte", { "any1", "any1" }, "boolean");
    new_ext1->AddFunction("gte", { "any1", "any1" }, "boolean");
    new_ext1->AddFunction("between", { "any1", "any1", "any1" }, "boolean");
    new_ext1->AddFunction("is_null", { "any1" }, "boolean");
    new_ext1->AddFunction("is_not_null", { "any1" }, "boolean");
    new_ext1->AddFunction("is_nan", { "fp32" }, "boolean");
    new_ext1->AddFunction("is_nan", { "fp64" }, "boolean");
    new_ext1->AddFunction("is_finite", { "fp32" }, "boolean");
    new_ext1->AddFunction("is_finite", { "fp64" }, "boolean");
    new_ext1->AddFunction("is_infinite", { "fp32" }, "boolean");
    new_ext1->AddFunction("is_infinite", { "fp64" }, "boolean");
    new_ext1->AddFunction("nullif", { "any1", "any1" }, "any1");
    new_ext1->AddFunction("coalesce", { "any1" }, "any1");
    new_ext1->AddFunction("least", { "any1" }, "any1");
    new_ext1->AddFunction("least_skip_null", { "any1" }, "any1");
    new_ext1->AddFunction("greatest", { "any1" }, "any1");
    new_ext1->AddFunction("greatest_skip_null", { "any1" }, "any1");

    SubstraitFunctionExt* new_ext2 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_geometry.yaml");
    new_ext2->AddFunction("point", { "fp64", "fp64" }, "u!geometry");
    new_ext2->AddFunction("make_line", { "u!geometry", "u!geometry" }, "u!geometry");
    new_ext2->AddFunction("x_coordinate", { "u!geometry" }, "fp64");
    new_ext2->AddFunction("y_coordinate", { "u!geometry" }, "fp64");
    new_ext2->AddFunction("num_points", { "u!geometry" }, "i64");
    new_ext2->AddFunction("is_empty", { "u!geometry" }, "boolean");
    new_ext2->AddFunction("is_closed", { "u!geometry" }, "boolean");
    new_ext2->AddFunction("is_simple", { "u!geometry" }, "boolean");
    new_ext2->AddFunction("is_ring", { "u!geometry" }, "boolean");
    new_ext2->AddFunction("geometry_type", { "u!geometry" }, "string");
    new_ext2->AddFunction("envelope", { "u!geometry" }, "u!geometry");
    new_ext2->AddFunction("dimension", { "u!geometry" }, "i8");
    new_ext2->AddFunction("is_valid", { "u!geometry" }, "boolean");
    new_ext2->AddFunction("collection_extract", { "u!geometry" }, "u!geometry");
    new_ext2->AddFunction("collection_extract", { "u!geometry", "i8" }, "u!geometry");
    new_ext2->AddFunction("flip_coordinates", { "u!geometry" }, "u!geometry");
    new_ext2->AddFunction("remove_repeated_points", { "u!geometry" }, "u!geometry");
    new_ext2->AddFunction("remove_repeated_points", { "u!geometry", "fp64" }, "u!geometry");
    new_ext2->AddFunction("buffer", { "u!geometry", "fp64" }, "u!geometry");
    new_ext2->AddFunction("centroid", { "u!geometry" }, "u!geometry");
    new_ext2->AddFunction("minimum_bounding_circle", { "u!geometry" }, "u!geometry");

    SubstraitFunctionExt* new_ext3 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_aggregate_approx.yaml");
    new_ext3->AddFunction("approx_count_distinct", { "any" }, "i64");

    SubstraitFunctionExt* new_ext4 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_aggregate_decimal_output.yaml");
    new_ext4->AddFunction("count", { "any" }, "decimal");
    new_ext4->AddFunction("count", {  }, "decimal");
    new_ext4->AddFunction("approx_count_distinct", { "any" }, "decimal");

    SubstraitFunctionExt* new_ext5 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_logarithmic.yaml");
    new_ext5->AddFunction("ln", { "i64" }, "fp64");
    new_ext5->AddFunction("ln", { "fp32" }, "fp32");
    new_ext5->AddFunction("ln", { "fp64" }, "fp64");
    new_ext5->AddFunction("ln", { "decimal" }, "fp64");
    new_ext5->AddFunction("log10", { "i64" }, "fp64");
    new_ext5->AddFunction("log10", { "fp32" }, "fp32");
    new_ext5->AddFunction("log10", { "fp64" }, "fp64");
    new_ext5->AddFunction("log10", { "decimal" }, "fp64");
    new_ext5->AddFunction("log2", { "i64" }, "fp64");
    new_ext5->AddFunction("log2", { "fp32" }, "fp32");
    new_ext5->AddFunction("log2", { "fp64" }, "fp64");
    new_ext5->AddFunction("log2", { "decimal" }, "fp64");
    new_ext5->AddFunction("logb", { "i64", "i64" }, "fp64");
    new_ext5->AddFunction("logb", { "fp32", "fp32" }, "fp32");
    new_ext5->AddFunction("logb", { "fp64", "fp64" }, "fp64");
    new_ext5->AddFunction("logb", { "decimal", "decimal" }, "fp64");
    new_ext5->AddFunction("log1p", { "fp32" }, "fp32");
    new_ext5->AddFunction("log1p", { "fp64" }, "fp64");
    new_ext5->AddFunction("log1p", { "decimal" }, "fp64");

    SubstraitFunctionExt* new_ext6 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/unknown.yaml");
    new_ext6->AddFunction("add", { "unknown", "unknown" }, "unknown");
    new_ext6->AddFunction("subtract", { "unknown", "unknown" }, "unknown");
    new_ext6->AddFunction("multiply", { "unknown", "unknown" }, "unknown");
    new_ext6->AddFunction("divide", { "unknown", "unknown" }, "unknown");
    new_ext6->AddFunction("modulus", { "unknown", "unknown" }, "unknown");
    new_ext6->AddFunction("sum", { "unknown" }, "unknown");
    new_ext6->AddFunction("avg", { "unknown" }, "unknown");
    new_ext6->AddFunction("min", { "unknown" }, "unknown");
    new_ext6->AddFunction("max", { "unknown" }, "unknown");
    new_ext6->AddFunction("count", { "unknown" }, "unknown");

    SubstraitFunctionExt* new_ext7 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_string.yaml");
    new_ext7->AddFunction("concat", { "varchar" }, "varchar");
    new_ext7->AddFunction("concat", { "string" }, "string");
    new_ext7->AddFunction("like", { "varchar", "varchar" }, "boolean");
    new_ext7->AddFunction("like", { "string", "string" }, "boolean");
    new_ext7->AddFunction("substring", { "varchar", "i32", "i32" }, "varchar");
    new_ext7->AddFunction("substring", { "string", "i32", "i32" }, "string");
    new_ext7->AddFunction("substring", { "fixedchar", "i32", "i32" }, "string");
    new_ext7->AddFunction("substring", { "varchar", "i32" }, "varchar");
    new_ext7->AddFunction("substring", { "string", "i32" }, "string");
    new_ext7->AddFunction("substring", { "fixedchar", "i32" }, "string");
    new_ext7->AddFunction("regexp_match_substring", { "varchar", "varchar", "i64", "i64", "i64" }, "varchar");
    new_ext7->AddFunction("regexp_match_substring", { "string", "string", "i64", "i64", "i64" }, "string");
    new_ext7->AddFunction("regexp_match_substring", { "string", "string" }, "string");
    new_ext7->AddFunction("regexp_match_substring_all", { "varchar", "varchar", "i64", "i64" }, "list>");
    new_ext7->AddFunction("regexp_match_substring_all", { "string", "string", "i64", "i64" }, "list");
    new_ext7->AddFunction("starts_with", { "varchar", "varchar" }, "boolean");
    new_ext7->AddFunction("starts_with", { "varchar", "string" }, "boolean");
    new_ext7->AddFunction("starts_with", { "varchar", "fixedchar" }, "boolean");
    new_ext7->AddFunction("starts_with", { "string", "string" }, "boolean");
    new_ext7->AddFunction("starts_with", { "string", "varchar" }, "boolean");
    new_ext7->AddFunction("starts_with", { "string", "fixedchar" }, "boolean");
    new_ext7->AddFunction("starts_with", { "fixedchar", "fixedchar" }, "boolean");
    new_ext7->AddFunction("starts_with", { "fixedchar", "string" }, "boolean");
    new_ext7->AddFunction("starts_with", { "fixedchar", "varchar" }, "boolean");
    new_ext7->AddFunction("ends_with", { "varchar", "varchar" }, "boolean");
    new_ext7->AddFunction("ends_with", { "varchar", "string" }, "boolean");
    new_ext7->AddFunction("ends_with", { "varchar", "fixedchar" }, "boolean");
    new_ext7->AddFunction("ends_with", { "string", "string" }, "boolean");
    new_ext7->AddFunction("ends_with", { "string", "varchar" }, "boolean");
    new_ext7->AddFunction("ends_with", { "string", "fixedchar" }, "boolean");
    new_ext7->AddFunction("ends_with", { "fixedchar", "fixedchar" }, "boolean");
    new_ext7->AddFunction("ends_with", { "fixedchar", "string" }, "boolean");
    new_ext7->AddFunction("ends_with", { "fixedchar", "varchar" }, "boolean");
    new_ext7->AddFunction("contains", { "varchar", "varchar" }, "boolean");
    new_ext7->AddFunction("contains", { "varchar", "string" }, "boolean");
    new_ext7->AddFunction("contains", { "varchar", "fixedchar" }, "boolean");
    new_ext7->AddFunction("contains", { "string", "string" }, "boolean");
    new_ext7->AddFunction("contains", { "string", "varchar" }, "boolean");
    new_ext7->AddFunction("contains", { "string", "fixedchar" }, "boolean");
    new_ext7->AddFunction("contains", { "fixedchar", "fixedchar" }, "boolean");
    new_ext7->AddFunction("contains", { "fixedchar", "string" }, "boolean");
    new_ext7->AddFunction("contains", { "fixedchar", "varchar" }, "boolean");
    new_ext7->AddFunction("strpos", { "string", "string" }, "i64");
    new_ext7->AddFunction("strpos", { "varchar", "varchar" }, "i64");
    new_ext7->AddFunction("strpos", { "fixedchar", "fixedchar" }, "i64");
    new_ext7->AddFunction("regexp_strpos", { "varchar", "varchar", "i64", "i64" }, "i64");
    new_ext7->AddFunction("regexp_strpos", { "string", "string", "i64", "i64" }, "i64");
    new_ext7->AddFunction("count_substring", { "string", "string" }, "i64");
    new_ext7->AddFunction("count_substring", { "varchar", "varchar" }, "i64");
    new_ext7->AddFunction("count_substring", { "fixedchar", "fixedchar" }, "i64");
    new_ext7->AddFunction("regexp_count_substring", { "string", "string", "i64" }, "i64");
    new_ext7->AddFunction("regexp_count_substring", { "varchar", "varchar", "i64" }, "i64");
    new_ext7->AddFunction("regexp_count_substring", { "fixedchar", "fixedchar", "i64" }, "i64");
    new_ext7->AddFunction("regexp_count_substring", { "string", "string" }, "i64");
    new_ext7->AddFunction("replace", { "string", "string", "string" }, "string");
    new_ext7->AddFunction("replace", { "varchar", "varchar", "varchar" }, "varchar");
    new_ext7->AddFunction("concat_ws", { "string", "string" }, "string");
    new_ext7->AddFunction("concat_ws", { "varchar", "varchar" }, "varchar");
    new_ext7->AddFunction("repeat", { "string", "i64" }, "string");
    new_ext7->AddFunction("repeat", { "varchar", "i64", "i64" }, "varchar");
    new_ext7->AddFunction("reverse", { "string" }, "string");
    new_ext7->AddFunction("reverse", { "varchar" }, "varchar");
    new_ext7->AddFunction("reverse", { "fixedchar" }, "fixedchar");
    new_ext7->AddFunction("replace_slice", { "string", "i64", "i64", "string" }, "string");
    new_ext7->AddFunction("replace_slice", { "varchar", "i64", "i64", "varchar" }, "varchar");
    new_ext7->AddFunction("lower", { "string" }, "string");
    new_ext7->AddFunction("lower", { "varchar" }, "varchar");
    new_ext7->AddFunction("lower", { "fixedchar" }, "fixedchar");
    new_ext7->AddFunction("upper", { "string" }, "string");
    new_ext7->AddFunction("upper", { "varchar" }, "varchar");
    new_ext7->AddFunction("upper", { "fixedchar" }, "fixedchar");
    new_ext7->AddFunction("swapcase", { "string" }, "string");
    new_ext7->AddFunction("swapcase", { "varchar" }, "varchar");
    new_ext7->AddFunction("swapcase", { "fixedchar" }, "fixedchar");
    new_ext7->AddFunction("capitalize", { "string" }, "string");
    new_ext7->AddFunction("capitalize", { "varchar" }, "varchar");
    new_ext7->AddFunction("capitalize", { "fixedchar" }, "fixedchar");
    new_ext7->AddFunction("title", { "string" }, "string");
    new_ext7->AddFunction("title", { "varchar" }, "varchar");
    new_ext7->AddFunction("title", { "fixedchar" }, "fixedchar");
    new_ext7->AddFunction("initcap", { "string" }, "string");
    new_ext7->AddFunction("initcap", { "varchar" }, "varchar");
    new_ext7->AddFunction("initcap", { "fixedchar" }, "fixedchar");
    new_ext7->AddFunction("char_length", { "string" }, "i64");
    new_ext7->AddFunction("char_length", { "varchar" }, "i64");
    new_ext7->AddFunction("char_length", { "fixedchar" }, "i64");
    new_ext7->AddFunction("bit_length", { "string" }, "i64");
    new_ext7->AddFunction("bit_length", { "varchar" }, "i64");
    new_ext7->AddFunction("bit_length", { "fixedchar" }, "i64");
    new_ext7->AddFunction("octet_length", { "string" }, "i64");
    new_ext7->AddFunction("octet_length", { "varchar" }, "i64");
    new_ext7->AddFunction("octet_length", { "fixedchar" }, "i64");
    new_ext7->AddFunction("regexp_replace", { "string", "string", "string", "i64", "i64" }, "string");
    new_ext7->AddFunction("regexp_replace", { "varchar", "varchar", "varchar", "i64", "i64" }, "varchar");
    new_ext7->AddFunction("regexp_replace", { "string", "string", "string" }, "string");
    new_ext7->AddFunction("ltrim", { "varchar", "varchar" }, "varchar");
    new_ext7->AddFunction("ltrim", { "string", "string" }, "string");
    new_ext7->AddFunction("rtrim", { "varchar", "varchar" }, "varchar");
    new_ext7->AddFunction("rtrim", { "string", "string" }, "string");
    new_ext7->AddFunction("trim", { "varchar", "varchar" }, "varchar");
    new_ext7->AddFunction("trim", { "string", "string" }, "string");
    new_ext7->AddFunction("lpad", { "varchar", "i32", "varchar" }, "varchar");
    new_ext7->AddFunction("lpad", { "string", "i32", "string" }, "string");
    new_ext7->AddFunction("rpad", { "varchar", "i32", "varchar" }, "varchar");
    new_ext7->AddFunction("rpad", { "string", "i32", "string" }, "string");
    new_ext7->AddFunction("center", { "varchar", "i32", "varchar" }, "varchar");
    new_ext7->AddFunction("center", { "string", "i32", "string" }, "string");
    new_ext7->AddFunction("left", { "varchar", "i32" }, "varchar");
    new_ext7->AddFunction("left", { "string", "i32" }, "string");
    new_ext7->AddFunction("right", { "varchar", "i32" }, "varchar");
    new_ext7->AddFunction("right", { "string", "i32" }, "string");
    new_ext7->AddFunction("string_split", { "varchar", "varchar" }, "list>");
    new_ext7->AddFunction("string_split", { "string", "string" }, "list");
    new_ext7->AddFunction("regexp_string_split", { "varchar", "varchar" }, "list>");
    new_ext7->AddFunction("regexp_string_split", { "string", "string" }, "list");
    new_ext7->AddFunction("string_agg", { "string", "string" }, "string");

    SubstraitFunctionExt* new_ext8 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_arithmetic.yaml");
    new_ext8->AddFunction("add", { "i8", "i8" }, "i8");
    new_ext8->AddFunction("add", { "i16", "i16" }, "i16");
    new_ext8->AddFunction("add", { "i32", "i32" }, "i32");
    new_ext8->AddFunction("add", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("add", { "fp32", "fp32" }, "fp32");
    new_ext8->AddFunction("add", { "fp64", "fp64" }, "fp64");
    new_ext8->AddFunction("subtract", { "i8", "i8" }, "i8");
    new_ext8->AddFunction("subtract", { "i16", "i16" }, "i16");
    new_ext8->AddFunction("subtract", { "i32", "i32" }, "i32");
    new_ext8->AddFunction("subtract", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("subtract", { "fp32", "fp32" }, "fp32");
    new_ext8->AddFunction("subtract", { "fp64", "fp64" }, "fp64");
    new_ext8->AddFunction("multiply", { "i8", "i8" }, "i8");
    new_ext8->AddFunction("multiply", { "i16", "i16" }, "i16");
    new_ext8->AddFunction("multiply", { "i32", "i32" }, "i32");
    new_ext8->AddFunction("multiply", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("multiply", { "fp32", "fp32" }, "fp32");
    new_ext8->AddFunction("multiply", { "fp64", "fp64" }, "fp64");
    new_ext8->AddFunction("divide", { "i8", "i8" }, "i8");
    new_ext8->AddFunction("divide", { "i16", "i16" }, "i16");
    new_ext8->AddFunction("divide", { "i32", "i32" }, "i32");
    new_ext8->AddFunction("divide", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("divide", { "fp32", "fp32" }, "fp32");
    new_ext8->AddFunction("divide", { "fp64", "fp64" }, "fp64");
    new_ext8->AddFunction("negate", { "i8" }, "i8");
    new_ext8->AddFunction("negate", { "i16" }, "i16");
    new_ext8->AddFunction("negate", { "i32" }, "i32");
    new_ext8->AddFunction("negate", { "i64" }, "i64");
    new_ext8->AddFunction("negate", { "fp32" }, "fp32");
    new_ext8->AddFunction("negate", { "fp64" }, "fp64");
    new_ext8->AddFunction("modulus", { "i8", "i8" }, "i8");
    new_ext8->AddFunction("modulus", { "i16", "i16" }, "i16");
    new_ext8->AddFunction("modulus", { "i32", "i32" }, "i32");
    new_ext8->AddFunction("modulus", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("power", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("power", { "fp32", "fp32" }, "fp32");
    new_ext8->AddFunction("power", { "fp64", "fp64" }, "fp64");
    new_ext8->AddFunction("sqrt", { "i64" }, "fp64");
    new_ext8->AddFunction("sqrt", { "fp32" }, "fp32");
    new_ext8->AddFunction("sqrt", { "fp64" }, "fp64");
    new_ext8->AddFunction("exp", { "i64" }, "fp64");
    new_ext8->AddFunction("exp", { "fp32" }, "fp32");
    new_ext8->AddFunction("exp", { "fp64" }, "fp64");
    new_ext8->AddFunction("cos", { "fp32" }, "fp32");
    new_ext8->AddFunction("cos", { "fp64" }, "fp64");
    new_ext8->AddFunction("sin", { "fp32" }, "fp32");
    new_ext8->AddFunction("sin", { "fp64" }, "fp64");
    new_ext8->AddFunction("tan", { "fp32" }, "fp32");
    new_ext8->AddFunction("tan", { "fp64" }, "fp64");
    new_ext8->AddFunction("cosh", { "fp32" }, "fp32");
    new_ext8->AddFunction("cosh", { "fp64" }, "fp64");
    new_ext8->AddFunction("sinh", { "fp32" }, "fp32");
    new_ext8->AddFunction("sinh", { "fp64" }, "fp64");
    new_ext8->AddFunction("tanh", { "fp32" }, "fp32");
    new_ext8->AddFunction("tanh", { "fp64" }, "fp64");
    new_ext8->AddFunction("acos", { "fp32" }, "fp32");
    new_ext8->AddFunction("acos", { "fp64" }, "fp64");
    new_ext8->AddFunction("asin", { "fp32" }, "fp32");
    new_ext8->AddFunction("asin", { "fp64" }, "fp64");
    new_ext8->AddFunction("atan", { "fp32" }, "fp32");
    new_ext8->AddFunction("atan", { "fp64" }, "fp64");
    new_ext8->AddFunction("acosh", { "fp32" }, "fp32");
    new_ext8->AddFunction("acosh", { "fp64" }, "fp64");
    new_ext8->AddFunction("asinh", { "fp32" }, "fp32");
    new_ext8->AddFunction("asinh", { "fp64" }, "fp64");
    new_ext8->AddFunction("atanh", { "fp32" }, "fp32");
    new_ext8->AddFunction("atanh", { "fp64" }, "fp64");
    new_ext8->AddFunction("atan2", { "fp32", "fp32" }, "fp32");
    new_ext8->AddFunction("atan2", { "fp64", "fp64" }, "fp64");
    new_ext8->AddFunction("radians", { "fp32" }, "fp32");
    new_ext8->AddFunction("radians", { "fp64" }, "fp64");
    new_ext8->AddFunction("degrees", { "fp32" }, "fp32");
    new_ext8->AddFunction("degrees", { "fp64" }, "fp64");
    new_ext8->AddFunction("abs", { "i8" }, "i8");
    new_ext8->AddFunction("abs", { "i16" }, "i16");
    new_ext8->AddFunction("abs", { "i32" }, "i32");
    new_ext8->AddFunction("abs", { "i64" }, "i64");
    new_ext8->AddFunction("abs", { "fp32" }, "fp32");
    new_ext8->AddFunction("abs", { "fp64" }, "fp64");
    new_ext8->AddFunction("sign", { "i8" }, "i8");
    new_ext8->AddFunction("sign", { "i16" }, "i16");
    new_ext8->AddFunction("sign", { "i32" }, "i32");
    new_ext8->AddFunction("sign", { "i64" }, "i64");
    new_ext8->AddFunction("sign", { "fp32" }, "fp32");
    new_ext8->AddFunction("sign", { "fp64" }, "fp64");
    new_ext8->AddFunction("factorial", { "i32" }, "i32");
    new_ext8->AddFunction("factorial", { "i64" }, "i64");
    new_ext8->AddFunction("bitwise_not", { "i8" }, "i8");
    new_ext8->AddFunction("bitwise_not", { "i16" }, "i16");
    new_ext8->AddFunction("bitwise_not", { "i32" }, "i32");
    new_ext8->AddFunction("bitwise_not", { "i64" }, "i64");
    new_ext8->AddFunction("bitwise_and", { "i8", "i8" }, "i8");
    new_ext8->AddFunction("bitwise_and", { "i16", "i16" }, "i16");
    new_ext8->AddFunction("bitwise_and", { "i32", "i32" }, "i32");
    new_ext8->AddFunction("bitwise_and", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("bitwise_or", { "i8", "i8" }, "i8");
    new_ext8->AddFunction("bitwise_or", { "i16", "i16" }, "i16");
    new_ext8->AddFunction("bitwise_or", { "i32", "i32" }, "i32");
    new_ext8->AddFunction("bitwise_or", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("bitwise_xor", { "i8", "i8" }, "i8");
    new_ext8->AddFunction("bitwise_xor", { "i16", "i16" }, "i16");
    new_ext8->AddFunction("bitwise_xor", { "i32", "i32" }, "i32");
    new_ext8->AddFunction("bitwise_xor", { "i64", "i64" }, "i64");
    new_ext8->AddFunction("sum", { "i8" }, "i64");
    new_ext8->AddFunction("sum", { "i16" }, "i64");
    new_ext8->AddFunction("sum", { "i32" }, "i64");
    new_ext8->AddFunction("sum", { "i64" }, "i64");
    new_ext8->AddFunction("sum", { "fp32" }, "fp64");
    new_ext8->AddFunction("sum", { "fp64" }, "fp64");
    new_ext8->AddFunction("sum0", { "i8" }, "i64");
    new_ext8->AddFunction("sum0", { "i16" }, "i64");
    new_ext8->AddFunction("sum0", { "i32" }, "i64");
    new_ext8->AddFunction("sum0", { "i64" }, "i64");
    new_ext8->AddFunction("sum0", { "fp32" }, "fp64");
    new_ext8->AddFunction("sum0", { "fp64" }, "fp64");
    new_ext8->AddFunction("avg", { "i8" }, "i8");
    new_ext8->AddFunction("avg", { "i16" }, "i16");
    new_ext8->AddFunction("avg", { "i32" }, "i32");
    new_ext8->AddFunction("avg", { "i64" }, "i64");
    new_ext8->AddFunction("avg", { "fp32" }, "fp32");
    new_ext8->AddFunction("avg", { "fp64" }, "fp64");
    new_ext8->AddFunction("min", { "i8" }, "i8");
    new_ext8->AddFunction("min", { "i16" }, "i16");
    new_ext8->AddFunction("min", { "i32" }, "i32");
    new_ext8->AddFunction("min", { "i64" }, "i64");
    new_ext8->AddFunction("min", { "fp32" }, "fp32");
    new_ext8->AddFunction("min", { "fp64" }, "fp64");
    new_ext8->AddFunction("max", { "i8" }, "i8");
    new_ext8->AddFunction("max", { "i16" }, "i16");
    new_ext8->AddFunction("max", { "i32" }, "i32");
    new_ext8->AddFunction("max", { "i64" }, "i64");
    new_ext8->AddFunction("max", { "fp32" }, "fp32");
    new_ext8->AddFunction("max", { "fp64" }, "fp64");
    new_ext8->AddFunction("product", { "i8" }, "i8");
    new_ext8->AddFunction("product", { "i16" }, "i16");
    new_ext8->AddFunction("product", { "i32" }, "i32");
    new_ext8->AddFunction("product", { "i64" }, "i64");
    new_ext8->AddFunction("product", { "fp32" }, "fp32");
    new_ext8->AddFunction("product", { "fp64" }, "fp64");
    new_ext8->AddFunction("std_dev", { "fp32" }, "fp32");
    new_ext8->AddFunction("std_dev", { "fp64" }, "fp64");
    new_ext8->AddFunction("variance", { "fp32" }, "fp32");
    new_ext8->AddFunction("variance", { "fp64" }, "fp64");
    new_ext8->AddFunction("corr", { "fp32", "fp32" }, "fp32");
    new_ext8->AddFunction("corr", { "fp64", "fp64" }, "fp64");
    new_ext8->AddFunction("mode", { "i8" }, "i8");
    new_ext8->AddFunction("mode", { "i16" }, "i16");
    new_ext8->AddFunction("mode", { "i32" }, "i32");
    new_ext8->AddFunction("mode", { "i64" }, "i64");
    new_ext8->AddFunction("mode", { "fp32" }, "fp32");
    new_ext8->AddFunction("mode", { "fp64" }, "fp64");
    new_ext8->AddFunction("median", { "i8" }, "i8");
    new_ext8->AddFunction("median", { "i16" }, "i16");
    new_ext8->AddFunction("median", { "i32" }, "i32");
    new_ext8->AddFunction("median", { "i64" }, "i64");
    new_ext8->AddFunction("median", { "fp32" }, "fp32");
    new_ext8->AddFunction("median", { "fp64" }, "fp64");
    new_ext8->AddFunction("quantile", { "i64", "any" }, "list");

    SubstraitFunctionExt* new_ext9 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_rounding.yaml");
    new_ext9->AddFunction("ceil", { "fp32" }, "fp32");
    new_ext9->AddFunction("ceil", { "fp64" }, "fp64");
    new_ext9->AddFunction("floor", { "fp32" }, "fp32");
    new_ext9->AddFunction("floor", { "fp64" }, "fp64");
    new_ext9->AddFunction("round", { "i8", "i32" }, "i8");
    new_ext9->AddFunction("round", { "i16", "i32" }, "i16");
    new_ext9->AddFunction("round", { "i32", "i32" }, "i32");
    new_ext9->AddFunction("round", { "i64", "i32" }, "i64");
    new_ext9->AddFunction("round", { "fp32", "i32" }, "fp32");
    new_ext9->AddFunction("round", { "fp64", "i32" }, "fp64");

    SubstraitFunctionExt* new_ext10 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_aggregate_generic.yaml");
    new_ext10->AddFunction("count", { "any" }, "i64");
    new_ext10->AddFunction("count", {  }, "i64");
    new_ext10->AddFunction("any_value", { "any1" }, "any1");

    SubstraitFunctionExt* new_ext11 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_boolean.yaml");
    new_ext11->AddFunction("or", { "boolean" }, "boolean");
    new_ext11->AddFunction("and", { "boolean" }, "boolean");
    new_ext11->AddFunction("and_not", { "boolean", "boolean" }, "boolean");
    new_ext11->AddFunction("xor", { "boolean", "boolean" }, "boolean");
    new_ext11->AddFunction("not", { "boolean" }, "boolean");
    new_ext11->AddFunction("bool_and", { "boolean" }, "boolean");
    new_ext11->AddFunction("bool_or", { "boolean" }, "boolean");

    SubstraitFunctionExt* new_ext12 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_arithmetic_decimal.yaml");
    new_ext12->AddFunction("add", { "decimal", "decimal" }, "decimal");
    new_ext12->AddFunction("subtract", { "decimal", "decimal" }, "decimal");
    new_ext12->AddFunction("multiply", { "decimal", "decimal" }, "decimal");
    new_ext12->AddFunction("divide", { "decimal", "decimal" }, "decimal");
    new_ext12->AddFunction("modulus", { "decimal", "decimal" }, "decimal");
    new_ext12->AddFunction("abs", { "decimal" }, "decimal");
    new_ext12->AddFunction("bitwise_and", { "decimal", "decimal" }, "decimal");
    new_ext12->AddFunction("bitwise_or", { "decimal", "decimal" }, "decimal");
    new_ext12->AddFunction("bitwise_xor", { "decimal", "decimal" }, "decimal");
    new_ext12->AddFunction("sqrt", { "decimal" }, "fp64");
    new_ext12->AddFunction("factorial", { "decimal" }, "decimal");
    new_ext12->AddFunction("power", { "decimal", "decimal" }, "fp64");
    new_ext12->AddFunction("sum", { "decimal" }, "decimal");
    new_ext12->AddFunction("avg", { "decimal" }, "decimal");
    new_ext12->AddFunction("min", { "decimal" }, "decimal");
    new_ext12->AddFunction("max", { "decimal" }, "decimal");
    new_ext12->AddFunction("sum0", { "decimal" }, "decimal");

    SubstraitFunctionExt* new_ext13 = RegisterFunctionExtension("subprojects/substrait-protocol/extensions/functions_set.yaml");
    new_ext13->AddFunction("index_in", { "any1", "list" }, "i64");

    return true;
  }

}
