// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skytether/substrait/extended_expression.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_skytether_2fsubstrait_2fextended_5fexpression_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_skytether_2fsubstrait_2fextended_5fexpression_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "skytether/substrait/algebra.pb.h"
#include "skytether/substrait/extensions/extensions.pb.h"
#include "skytether/substrait/plan.pb.h"
#include "skytether/substrait/type.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_skytether_2fsubstrait_2fextended_5fexpression_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_skytether_2fsubstrait_2fextended_5fexpression_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_skytether_2fsubstrait_2fextended_5fexpression_2eproto;
namespace skytether {
namespace substrait {
class ExpressionReference;
struct ExpressionReferenceDefaultTypeInternal;
extern ExpressionReferenceDefaultTypeInternal _ExpressionReference_default_instance_;
class ExtendedExpression;
struct ExtendedExpressionDefaultTypeInternal;
extern ExtendedExpressionDefaultTypeInternal _ExtendedExpression_default_instance_;
}  // namespace substrait
}  // namespace skytether
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace skytether {
namespace substrait {

// ===================================================================


// -------------------------------------------------------------------

class ExpressionReference final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:skytether.substrait.ExpressionReference) */ {
 public:
  inline ExpressionReference() : ExpressionReference(nullptr) {}
  ~ExpressionReference() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExpressionReference(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExpressionReference(const ExpressionReference& from) : ExpressionReference(nullptr, from) {}
  inline ExpressionReference(ExpressionReference&& from) noexcept
      : ExpressionReference(nullptr, std::move(from)) {}
  inline ExpressionReference& operator=(const ExpressionReference& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExpressionReference& operator=(ExpressionReference&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExpressionReference& default_instance() {
    return *internal_default_instance();
  }
  enum ExprTypeCase {
    kExpression = 1,
    kMeasure = 2,
    EXPR_TYPE_NOT_SET = 0,
  };
  static inline const ExpressionReference* internal_default_instance() {
    return reinterpret_cast<const ExpressionReference*>(
        &_ExpressionReference_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ExpressionReference& a, ExpressionReference& b) { a.Swap(&b); }
  inline void Swap(ExpressionReference* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExpressionReference* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExpressionReference* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ExpressionReference>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExpressionReference& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExpressionReference& from) { ExpressionReference::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExpressionReference* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "skytether.substrait.ExpressionReference"; }

 protected:
  explicit ExpressionReference(::google::protobuf::Arena* arena);
  ExpressionReference(::google::protobuf::Arena* arena, const ExpressionReference& from);
  ExpressionReference(::google::protobuf::Arena* arena, ExpressionReference&& from) noexcept
      : ExpressionReference(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOutputNamesFieldNumber = 3,
    kExpressionFieldNumber = 1,
    kMeasureFieldNumber = 2,
  };
  // repeated string output_names = 3 [json_name = "outputNames"];
  int output_names_size() const;
  private:
  int _internal_output_names_size() const;

  public:
  void clear_output_names() ;
  const std::string& output_names(int index) const;
  std::string* mutable_output_names(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_output_names(int index, Arg_&& value, Args_... args);
  std::string* add_output_names();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_output_names(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& output_names() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_output_names();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_output_names() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_output_names();

  public:
  // .skytether.substrait.Expression expression = 1 [json_name = "expression"];
  bool has_expression() const;
  private:
  bool _internal_has_expression() const;

  public:
  void clear_expression() ;
  const ::skytether::substrait::Expression& expression() const;
  PROTOBUF_NODISCARD ::skytether::substrait::Expression* release_expression();
  ::skytether::substrait::Expression* mutable_expression();
  void set_allocated_expression(::skytether::substrait::Expression* value);
  void unsafe_arena_set_allocated_expression(::skytether::substrait::Expression* value);
  ::skytether::substrait::Expression* unsafe_arena_release_expression();

  private:
  const ::skytether::substrait::Expression& _internal_expression() const;
  ::skytether::substrait::Expression* _internal_mutable_expression();

  public:
  // .skytether.substrait.AggregateFunction measure = 2 [json_name = "measure"];
  bool has_measure() const;
  private:
  bool _internal_has_measure() const;

  public:
  void clear_measure() ;
  const ::skytether::substrait::AggregateFunction& measure() const;
  PROTOBUF_NODISCARD ::skytether::substrait::AggregateFunction* release_measure();
  ::skytether::substrait::AggregateFunction* mutable_measure();
  void set_allocated_measure(::skytether::substrait::AggregateFunction* value);
  void unsafe_arena_set_allocated_measure(::skytether::substrait::AggregateFunction* value);
  ::skytether::substrait::AggregateFunction* unsafe_arena_release_measure();

  private:
  const ::skytether::substrait::AggregateFunction& _internal_measure() const;
  ::skytether::substrait::AggregateFunction* _internal_mutable_measure();

  public:
  void clear_expr_type();
  ExprTypeCase expr_type_case() const;
  // @@protoc_insertion_point(class_scope:skytether.substrait.ExpressionReference)
 private:
  class _Internal;
  void set_has_expression();
  void set_has_measure();
  inline bool has_expr_type() const;
  inline void clear_has_expr_type();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 2,
      60, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ExpressionReference_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ExpressionReference& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> output_names_;
    union ExprTypeUnion {
      constexpr ExprTypeUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::skytether::substrait::Expression* expression_;
      ::skytether::substrait::AggregateFunction* measure_;
    } expr_type_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_skytether_2fsubstrait_2fextended_5fexpression_2eproto;
};
// -------------------------------------------------------------------

class ExtendedExpression final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:skytether.substrait.ExtendedExpression) */ {
 public:
  inline ExtendedExpression() : ExtendedExpression(nullptr) {}
  ~ExtendedExpression() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExtendedExpression(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExtendedExpression(const ExtendedExpression& from) : ExtendedExpression(nullptr, from) {}
  inline ExtendedExpression(ExtendedExpression&& from) noexcept
      : ExtendedExpression(nullptr, std::move(from)) {}
  inline ExtendedExpression& operator=(const ExtendedExpression& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExtendedExpression& operator=(ExtendedExpression&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExtendedExpression& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExtendedExpression* internal_default_instance() {
    return reinterpret_cast<const ExtendedExpression*>(
        &_ExtendedExpression_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ExtendedExpression& a, ExtendedExpression& b) { a.Swap(&b); }
  inline void Swap(ExtendedExpression* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExtendedExpression* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExtendedExpression* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ExtendedExpression>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExtendedExpression& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExtendedExpression& from) { ExtendedExpression::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExtendedExpression* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "skytether.substrait.ExtendedExpression"; }

 protected:
  explicit ExtendedExpression(::google::protobuf::Arena* arena);
  ExtendedExpression(::google::protobuf::Arena* arena, const ExtendedExpression& from);
  ExtendedExpression(::google::protobuf::Arena* arena, ExtendedExpression&& from) noexcept
      : ExtendedExpression(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExtensionUrisFieldNumber = 1,
    kExtensionsFieldNumber = 2,
    kReferredExprFieldNumber = 3,
    kExpectedTypeUrlsFieldNumber = 6,
    kBaseSchemaFieldNumber = 4,
    kAdvancedExtensionsFieldNumber = 5,
    kVersionFieldNumber = 7,
  };
  // repeated .skytether.substrait.extensions.SimpleExtensionURI extension_uris = 1 [json_name = "extensionUris"];
  int extension_uris_size() const;
  private:
  int _internal_extension_uris_size() const;

  public:
  void clear_extension_uris() ;
  ::skytether::substrait::extensions::SimpleExtensionURI* mutable_extension_uris(int index);
  ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionURI>* mutable_extension_uris();

  private:
  const ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionURI>& _internal_extension_uris() const;
  ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionURI>* _internal_mutable_extension_uris();
  public:
  const ::skytether::substrait::extensions::SimpleExtensionURI& extension_uris(int index) const;
  ::skytether::substrait::extensions::SimpleExtensionURI* add_extension_uris();
  const ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionURI>& extension_uris() const;
  // repeated .skytether.substrait.extensions.SimpleExtensionDeclaration extensions = 2 [json_name = "extensions"];
  int extensions_size() const;
  private:
  int _internal_extensions_size() const;

  public:
  void clear_extensions() ;
  ::skytether::substrait::extensions::SimpleExtensionDeclaration* mutable_extensions(int index);
  ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionDeclaration>* mutable_extensions();

  private:
  const ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionDeclaration>& _internal_extensions() const;
  ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionDeclaration>* _internal_mutable_extensions();
  public:
  const ::skytether::substrait::extensions::SimpleExtensionDeclaration& extensions(int index) const;
  ::skytether::substrait::extensions::SimpleExtensionDeclaration* add_extensions();
  const ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionDeclaration>& extensions() const;
  // repeated .skytether.substrait.ExpressionReference referred_expr = 3 [json_name = "referredExpr"];
  int referred_expr_size() const;
  private:
  int _internal_referred_expr_size() const;

  public:
  void clear_referred_expr() ;
  ::skytether::substrait::ExpressionReference* mutable_referred_expr(int index);
  ::google::protobuf::RepeatedPtrField<::skytether::substrait::ExpressionReference>* mutable_referred_expr();

  private:
  const ::google::protobuf::RepeatedPtrField<::skytether::substrait::ExpressionReference>& _internal_referred_expr() const;
  ::google::protobuf::RepeatedPtrField<::skytether::substrait::ExpressionReference>* _internal_mutable_referred_expr();
  public:
  const ::skytether::substrait::ExpressionReference& referred_expr(int index) const;
  ::skytether::substrait::ExpressionReference* add_referred_expr();
  const ::google::protobuf::RepeatedPtrField<::skytether::substrait::ExpressionReference>& referred_expr() const;
  // repeated string expected_type_urls = 6 [json_name = "expectedTypeUrls"];
  int expected_type_urls_size() const;
  private:
  int _internal_expected_type_urls_size() const;

  public:
  void clear_expected_type_urls() ;
  const std::string& expected_type_urls(int index) const;
  std::string* mutable_expected_type_urls(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_expected_type_urls(int index, Arg_&& value, Args_... args);
  std::string* add_expected_type_urls();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_expected_type_urls(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& expected_type_urls() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_expected_type_urls();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_expected_type_urls() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_expected_type_urls();

  public:
  // .skytether.substrait.NamedStruct base_schema = 4 [json_name = "baseSchema"];
  bool has_base_schema() const;
  void clear_base_schema() ;
  const ::skytether::substrait::NamedStruct& base_schema() const;
  PROTOBUF_NODISCARD ::skytether::substrait::NamedStruct* release_base_schema();
  ::skytether::substrait::NamedStruct* mutable_base_schema();
  void set_allocated_base_schema(::skytether::substrait::NamedStruct* value);
  void unsafe_arena_set_allocated_base_schema(::skytether::substrait::NamedStruct* value);
  ::skytether::substrait::NamedStruct* unsafe_arena_release_base_schema();

  private:
  const ::skytether::substrait::NamedStruct& _internal_base_schema() const;
  ::skytether::substrait::NamedStruct* _internal_mutable_base_schema();

  public:
  // .skytether.substrait.extensions.AdvancedExtension advanced_extensions = 5 [json_name = "advancedExtensions"];
  bool has_advanced_extensions() const;
  void clear_advanced_extensions() ;
  const ::skytether::substrait::extensions::AdvancedExtension& advanced_extensions() const;
  PROTOBUF_NODISCARD ::skytether::substrait::extensions::AdvancedExtension* release_advanced_extensions();
  ::skytether::substrait::extensions::AdvancedExtension* mutable_advanced_extensions();
  void set_allocated_advanced_extensions(::skytether::substrait::extensions::AdvancedExtension* value);
  void unsafe_arena_set_allocated_advanced_extensions(::skytether::substrait::extensions::AdvancedExtension* value);
  ::skytether::substrait::extensions::AdvancedExtension* unsafe_arena_release_advanced_extensions();

  private:
  const ::skytether::substrait::extensions::AdvancedExtension& _internal_advanced_extensions() const;
  ::skytether::substrait::extensions::AdvancedExtension* _internal_mutable_advanced_extensions();

  public:
  // .skytether.substrait.Version version = 7 [json_name = "version"];
  bool has_version() const;
  void clear_version() ;
  const ::skytether::substrait::Version& version() const;
  PROTOBUF_NODISCARD ::skytether::substrait::Version* release_version();
  ::skytether::substrait::Version* mutable_version();
  void set_allocated_version(::skytether::substrait::Version* value);
  void unsafe_arena_set_allocated_version(::skytether::substrait::Version* value);
  ::skytether::substrait::Version* unsafe_arena_release_version();

  private:
  const ::skytether::substrait::Version& _internal_version() const;
  ::skytether::substrait::Version* _internal_mutable_version();

  public:
  // @@protoc_insertion_point(class_scope:skytether.substrait.ExtendedExpression)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 6,
      65, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ExtendedExpression_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ExtendedExpression& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::skytether::substrait::extensions::SimpleExtensionURI > extension_uris_;
    ::google::protobuf::RepeatedPtrField< ::skytether::substrait::extensions::SimpleExtensionDeclaration > extensions_;
    ::google::protobuf::RepeatedPtrField< ::skytether::substrait::ExpressionReference > referred_expr_;
    ::google::protobuf::RepeatedPtrField<std::string> expected_type_urls_;
    ::skytether::substrait::NamedStruct* base_schema_;
    ::skytether::substrait::extensions::AdvancedExtension* advanced_extensions_;
    ::skytether::substrait::Version* version_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_skytether_2fsubstrait_2fextended_5fexpression_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExpressionReference

// .skytether.substrait.Expression expression = 1 [json_name = "expression"];
inline bool ExpressionReference::has_expression() const {
  return expr_type_case() == kExpression;
}
inline bool ExpressionReference::_internal_has_expression() const {
  return expr_type_case() == kExpression;
}
inline void ExpressionReference::set_has_expression() {
  _impl_._oneof_case_[0] = kExpression;
}
inline ::skytether::substrait::Expression* ExpressionReference::release_expression() {
  // @@protoc_insertion_point(field_release:skytether.substrait.ExpressionReference.expression)
  if (expr_type_case() == kExpression) {
    clear_has_expr_type();
    auto* temp = _impl_.expr_type_.expression_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.expr_type_.expression_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::skytether::substrait::Expression& ExpressionReference::_internal_expression() const {
  return expr_type_case() == kExpression ? *_impl_.expr_type_.expression_ : reinterpret_cast<::skytether::substrait::Expression&>(::skytether::substrait::_Expression_default_instance_);
}
inline const ::skytether::substrait::Expression& ExpressionReference::expression() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExpressionReference.expression)
  return _internal_expression();
}
inline ::skytether::substrait::Expression* ExpressionReference::unsafe_arena_release_expression() {
  // @@protoc_insertion_point(field_unsafe_arena_release:skytether.substrait.ExpressionReference.expression)
  if (expr_type_case() == kExpression) {
    clear_has_expr_type();
    auto* temp = _impl_.expr_type_.expression_;
    _impl_.expr_type_.expression_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ExpressionReference::unsafe_arena_set_allocated_expression(::skytether::substrait::Expression* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_expr_type();
  if (value) {
    set_has_expression();
    _impl_.expr_type_.expression_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:skytether.substrait.ExpressionReference.expression)
}
inline ::skytether::substrait::Expression* ExpressionReference::_internal_mutable_expression() {
  if (expr_type_case() != kExpression) {
    clear_expr_type();
    set_has_expression();
    _impl_.expr_type_.expression_ =
        ::google::protobuf::Message::DefaultConstruct<::skytether::substrait::Expression>(GetArena());
  }
  return _impl_.expr_type_.expression_;
}
inline ::skytether::substrait::Expression* ExpressionReference::mutable_expression() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::skytether::substrait::Expression* _msg = _internal_mutable_expression();
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExpressionReference.expression)
  return _msg;
}

// .skytether.substrait.AggregateFunction measure = 2 [json_name = "measure"];
inline bool ExpressionReference::has_measure() const {
  return expr_type_case() == kMeasure;
}
inline bool ExpressionReference::_internal_has_measure() const {
  return expr_type_case() == kMeasure;
}
inline void ExpressionReference::set_has_measure() {
  _impl_._oneof_case_[0] = kMeasure;
}
inline ::skytether::substrait::AggregateFunction* ExpressionReference::release_measure() {
  // @@protoc_insertion_point(field_release:skytether.substrait.ExpressionReference.measure)
  if (expr_type_case() == kMeasure) {
    clear_has_expr_type();
    auto* temp = _impl_.expr_type_.measure_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.expr_type_.measure_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::skytether::substrait::AggregateFunction& ExpressionReference::_internal_measure() const {
  return expr_type_case() == kMeasure ? *_impl_.expr_type_.measure_ : reinterpret_cast<::skytether::substrait::AggregateFunction&>(::skytether::substrait::_AggregateFunction_default_instance_);
}
inline const ::skytether::substrait::AggregateFunction& ExpressionReference::measure() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExpressionReference.measure)
  return _internal_measure();
}
inline ::skytether::substrait::AggregateFunction* ExpressionReference::unsafe_arena_release_measure() {
  // @@protoc_insertion_point(field_unsafe_arena_release:skytether.substrait.ExpressionReference.measure)
  if (expr_type_case() == kMeasure) {
    clear_has_expr_type();
    auto* temp = _impl_.expr_type_.measure_;
    _impl_.expr_type_.measure_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ExpressionReference::unsafe_arena_set_allocated_measure(::skytether::substrait::AggregateFunction* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_expr_type();
  if (value) {
    set_has_measure();
    _impl_.expr_type_.measure_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:skytether.substrait.ExpressionReference.measure)
}
inline ::skytether::substrait::AggregateFunction* ExpressionReference::_internal_mutable_measure() {
  if (expr_type_case() != kMeasure) {
    clear_expr_type();
    set_has_measure();
    _impl_.expr_type_.measure_ =
        ::google::protobuf::Message::DefaultConstruct<::skytether::substrait::AggregateFunction>(GetArena());
  }
  return _impl_.expr_type_.measure_;
}
inline ::skytether::substrait::AggregateFunction* ExpressionReference::mutable_measure() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::skytether::substrait::AggregateFunction* _msg = _internal_mutable_measure();
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExpressionReference.measure)
  return _msg;
}

// repeated string output_names = 3 [json_name = "outputNames"];
inline int ExpressionReference::_internal_output_names_size() const {
  return _internal_output_names().size();
}
inline int ExpressionReference::output_names_size() const {
  return _internal_output_names_size();
}
inline void ExpressionReference::clear_output_names() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.output_names_.Clear();
}
inline std::string* ExpressionReference::add_output_names() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_output_names()->Add();
  // @@protoc_insertion_point(field_add_mutable:skytether.substrait.ExpressionReference.output_names)
  return _s;
}
inline const std::string& ExpressionReference::output_names(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExpressionReference.output_names)
  return _internal_output_names().Get(index);
}
inline std::string* ExpressionReference::mutable_output_names(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExpressionReference.output_names)
  return _internal_mutable_output_names()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ExpressionReference::set_output_names(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_output_names()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:skytether.substrait.ExpressionReference.output_names)
}
template <typename Arg_, typename... Args_>
inline void ExpressionReference::add_output_names(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_output_names(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:skytether.substrait.ExpressionReference.output_names)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExpressionReference::output_names() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skytether.substrait.ExpressionReference.output_names)
  return _internal_output_names();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExpressionReference::mutable_output_names() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skytether.substrait.ExpressionReference.output_names)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_output_names();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExpressionReference::_internal_output_names() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.output_names_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExpressionReference::_internal_mutable_output_names() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.output_names_;
}

inline bool ExpressionReference::has_expr_type() const {
  return expr_type_case() != EXPR_TYPE_NOT_SET;
}
inline void ExpressionReference::clear_has_expr_type() {
  _impl_._oneof_case_[0] = EXPR_TYPE_NOT_SET;
}
inline ExpressionReference::ExprTypeCase ExpressionReference::expr_type_case() const {
  return ExpressionReference::ExprTypeCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ExtendedExpression

// .skytether.substrait.Version version = 7 [json_name = "version"];
inline bool ExtendedExpression::has_version() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.version_ != nullptr);
  return value;
}
inline const ::skytether::substrait::Version& ExtendedExpression::_internal_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::skytether::substrait::Version* p = _impl_.version_;
  return p != nullptr ? *p : reinterpret_cast<const ::skytether::substrait::Version&>(::skytether::substrait::_Version_default_instance_);
}
inline const ::skytether::substrait::Version& ExtendedExpression::version() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExtendedExpression.version)
  return _internal_version();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_version(::skytether::substrait::Version* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.version_);
  }
  _impl_.version_ = reinterpret_cast<::skytether::substrait::Version*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:skytether.substrait.ExtendedExpression.version)
}
inline ::skytether::substrait::Version* ExtendedExpression::release_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::skytether::substrait::Version* released = _impl_.version_;
  _impl_.version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::skytether::substrait::Version* ExtendedExpression::unsafe_arena_release_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:skytether.substrait.ExtendedExpression.version)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::skytether::substrait::Version* temp = _impl_.version_;
  _impl_.version_ = nullptr;
  return temp;
}
inline ::skytether::substrait::Version* ExtendedExpression::_internal_mutable_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.version_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::skytether::substrait::Version>(GetArena());
    _impl_.version_ = reinterpret_cast<::skytether::substrait::Version*>(p);
  }
  return _impl_.version_;
}
inline ::skytether::substrait::Version* ExtendedExpression::mutable_version() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::skytether::substrait::Version* _msg = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExtendedExpression.version)
  return _msg;
}
inline void ExtendedExpression::set_allocated_version(::skytether::substrait::Version* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.version_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.version_ = reinterpret_cast<::skytether::substrait::Version*>(value);
  // @@protoc_insertion_point(field_set_allocated:skytether.substrait.ExtendedExpression.version)
}

// repeated .skytether.substrait.extensions.SimpleExtensionURI extension_uris = 1 [json_name = "extensionUris"];
inline int ExtendedExpression::_internal_extension_uris_size() const {
  return _internal_extension_uris().size();
}
inline int ExtendedExpression::extension_uris_size() const {
  return _internal_extension_uris_size();
}
inline ::skytether::substrait::extensions::SimpleExtensionURI* ExtendedExpression::mutable_extension_uris(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExtendedExpression.extension_uris)
  return _internal_mutable_extension_uris()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionURI>* ExtendedExpression::mutable_extension_uris()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skytether.substrait.ExtendedExpression.extension_uris)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_extension_uris();
}
inline const ::skytether::substrait::extensions::SimpleExtensionURI& ExtendedExpression::extension_uris(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExtendedExpression.extension_uris)
  return _internal_extension_uris().Get(index);
}
inline ::skytether::substrait::extensions::SimpleExtensionURI* ExtendedExpression::add_extension_uris() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::skytether::substrait::extensions::SimpleExtensionURI* _add = _internal_mutable_extension_uris()->Add();
  // @@protoc_insertion_point(field_add:skytether.substrait.ExtendedExpression.extension_uris)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionURI>& ExtendedExpression::extension_uris() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skytether.substrait.ExtendedExpression.extension_uris)
  return _internal_extension_uris();
}
inline const ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionURI>&
ExtendedExpression::_internal_extension_uris() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.extension_uris_;
}
inline ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionURI>*
ExtendedExpression::_internal_mutable_extension_uris() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.extension_uris_;
}

// repeated .skytether.substrait.extensions.SimpleExtensionDeclaration extensions = 2 [json_name = "extensions"];
inline int ExtendedExpression::_internal_extensions_size() const {
  return _internal_extensions().size();
}
inline int ExtendedExpression::extensions_size() const {
  return _internal_extensions_size();
}
inline ::skytether::substrait::extensions::SimpleExtensionDeclaration* ExtendedExpression::mutable_extensions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExtendedExpression.extensions)
  return _internal_mutable_extensions()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionDeclaration>* ExtendedExpression::mutable_extensions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skytether.substrait.ExtendedExpression.extensions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_extensions();
}
inline const ::skytether::substrait::extensions::SimpleExtensionDeclaration& ExtendedExpression::extensions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExtendedExpression.extensions)
  return _internal_extensions().Get(index);
}
inline ::skytether::substrait::extensions::SimpleExtensionDeclaration* ExtendedExpression::add_extensions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::skytether::substrait::extensions::SimpleExtensionDeclaration* _add = _internal_mutable_extensions()->Add();
  // @@protoc_insertion_point(field_add:skytether.substrait.ExtendedExpression.extensions)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionDeclaration>& ExtendedExpression::extensions() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skytether.substrait.ExtendedExpression.extensions)
  return _internal_extensions();
}
inline const ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionDeclaration>&
ExtendedExpression::_internal_extensions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.extensions_;
}
inline ::google::protobuf::RepeatedPtrField<::skytether::substrait::extensions::SimpleExtensionDeclaration>*
ExtendedExpression::_internal_mutable_extensions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.extensions_;
}

// repeated .skytether.substrait.ExpressionReference referred_expr = 3 [json_name = "referredExpr"];
inline int ExtendedExpression::_internal_referred_expr_size() const {
  return _internal_referred_expr().size();
}
inline int ExtendedExpression::referred_expr_size() const {
  return _internal_referred_expr_size();
}
inline void ExtendedExpression::clear_referred_expr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.referred_expr_.Clear();
}
inline ::skytether::substrait::ExpressionReference* ExtendedExpression::mutable_referred_expr(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExtendedExpression.referred_expr)
  return _internal_mutable_referred_expr()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::skytether::substrait::ExpressionReference>* ExtendedExpression::mutable_referred_expr()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skytether.substrait.ExtendedExpression.referred_expr)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_referred_expr();
}
inline const ::skytether::substrait::ExpressionReference& ExtendedExpression::referred_expr(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExtendedExpression.referred_expr)
  return _internal_referred_expr().Get(index);
}
inline ::skytether::substrait::ExpressionReference* ExtendedExpression::add_referred_expr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::skytether::substrait::ExpressionReference* _add = _internal_mutable_referred_expr()->Add();
  // @@protoc_insertion_point(field_add:skytether.substrait.ExtendedExpression.referred_expr)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::skytether::substrait::ExpressionReference>& ExtendedExpression::referred_expr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skytether.substrait.ExtendedExpression.referred_expr)
  return _internal_referred_expr();
}
inline const ::google::protobuf::RepeatedPtrField<::skytether::substrait::ExpressionReference>&
ExtendedExpression::_internal_referred_expr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.referred_expr_;
}
inline ::google::protobuf::RepeatedPtrField<::skytether::substrait::ExpressionReference>*
ExtendedExpression::_internal_mutable_referred_expr() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.referred_expr_;
}

// .skytether.substrait.NamedStruct base_schema = 4 [json_name = "baseSchema"];
inline bool ExtendedExpression::has_base_schema() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.base_schema_ != nullptr);
  return value;
}
inline const ::skytether::substrait::NamedStruct& ExtendedExpression::_internal_base_schema() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::skytether::substrait::NamedStruct* p = _impl_.base_schema_;
  return p != nullptr ? *p : reinterpret_cast<const ::skytether::substrait::NamedStruct&>(::skytether::substrait::_NamedStruct_default_instance_);
}
inline const ::skytether::substrait::NamedStruct& ExtendedExpression::base_schema() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExtendedExpression.base_schema)
  return _internal_base_schema();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_base_schema(::skytether::substrait::NamedStruct* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.base_schema_);
  }
  _impl_.base_schema_ = reinterpret_cast<::skytether::substrait::NamedStruct*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:skytether.substrait.ExtendedExpression.base_schema)
}
inline ::skytether::substrait::NamedStruct* ExtendedExpression::release_base_schema() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::skytether::substrait::NamedStruct* released = _impl_.base_schema_;
  _impl_.base_schema_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::skytether::substrait::NamedStruct* ExtendedExpression::unsafe_arena_release_base_schema() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:skytether.substrait.ExtendedExpression.base_schema)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::skytether::substrait::NamedStruct* temp = _impl_.base_schema_;
  _impl_.base_schema_ = nullptr;
  return temp;
}
inline ::skytether::substrait::NamedStruct* ExtendedExpression::_internal_mutable_base_schema() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.base_schema_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::skytether::substrait::NamedStruct>(GetArena());
    _impl_.base_schema_ = reinterpret_cast<::skytether::substrait::NamedStruct*>(p);
  }
  return _impl_.base_schema_;
}
inline ::skytether::substrait::NamedStruct* ExtendedExpression::mutable_base_schema() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::skytether::substrait::NamedStruct* _msg = _internal_mutable_base_schema();
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExtendedExpression.base_schema)
  return _msg;
}
inline void ExtendedExpression::set_allocated_base_schema(::skytether::substrait::NamedStruct* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.base_schema_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.base_schema_ = reinterpret_cast<::skytether::substrait::NamedStruct*>(value);
  // @@protoc_insertion_point(field_set_allocated:skytether.substrait.ExtendedExpression.base_schema)
}

// .skytether.substrait.extensions.AdvancedExtension advanced_extensions = 5 [json_name = "advancedExtensions"];
inline bool ExtendedExpression::has_advanced_extensions() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.advanced_extensions_ != nullptr);
  return value;
}
inline const ::skytether::substrait::extensions::AdvancedExtension& ExtendedExpression::_internal_advanced_extensions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::skytether::substrait::extensions::AdvancedExtension* p = _impl_.advanced_extensions_;
  return p != nullptr ? *p : reinterpret_cast<const ::skytether::substrait::extensions::AdvancedExtension&>(::skytether::substrait::extensions::_AdvancedExtension_default_instance_);
}
inline const ::skytether::substrait::extensions::AdvancedExtension& ExtendedExpression::advanced_extensions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExtendedExpression.advanced_extensions)
  return _internal_advanced_extensions();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_advanced_extensions(::skytether::substrait::extensions::AdvancedExtension* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.advanced_extensions_);
  }
  _impl_.advanced_extensions_ = reinterpret_cast<::skytether::substrait::extensions::AdvancedExtension*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:skytether.substrait.ExtendedExpression.advanced_extensions)
}
inline ::skytether::substrait::extensions::AdvancedExtension* ExtendedExpression::release_advanced_extensions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::skytether::substrait::extensions::AdvancedExtension* released = _impl_.advanced_extensions_;
  _impl_.advanced_extensions_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::skytether::substrait::extensions::AdvancedExtension* ExtendedExpression::unsafe_arena_release_advanced_extensions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:skytether.substrait.ExtendedExpression.advanced_extensions)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::skytether::substrait::extensions::AdvancedExtension* temp = _impl_.advanced_extensions_;
  _impl_.advanced_extensions_ = nullptr;
  return temp;
}
inline ::skytether::substrait::extensions::AdvancedExtension* ExtendedExpression::_internal_mutable_advanced_extensions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.advanced_extensions_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::skytether::substrait::extensions::AdvancedExtension>(GetArena());
    _impl_.advanced_extensions_ = reinterpret_cast<::skytether::substrait::extensions::AdvancedExtension*>(p);
  }
  return _impl_.advanced_extensions_;
}
inline ::skytether::substrait::extensions::AdvancedExtension* ExtendedExpression::mutable_advanced_extensions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::skytether::substrait::extensions::AdvancedExtension* _msg = _internal_mutable_advanced_extensions();
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExtendedExpression.advanced_extensions)
  return _msg;
}
inline void ExtendedExpression::set_allocated_advanced_extensions(::skytether::substrait::extensions::AdvancedExtension* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.advanced_extensions_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.advanced_extensions_ = reinterpret_cast<::skytether::substrait::extensions::AdvancedExtension*>(value);
  // @@protoc_insertion_point(field_set_allocated:skytether.substrait.ExtendedExpression.advanced_extensions)
}

// repeated string expected_type_urls = 6 [json_name = "expectedTypeUrls"];
inline int ExtendedExpression::_internal_expected_type_urls_size() const {
  return _internal_expected_type_urls().size();
}
inline int ExtendedExpression::expected_type_urls_size() const {
  return _internal_expected_type_urls_size();
}
inline void ExtendedExpression::clear_expected_type_urls() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expected_type_urls_.Clear();
}
inline std::string* ExtendedExpression::add_expected_type_urls() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_expected_type_urls()->Add();
  // @@protoc_insertion_point(field_add_mutable:skytether.substrait.ExtendedExpression.expected_type_urls)
  return _s;
}
inline const std::string& ExtendedExpression::expected_type_urls(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skytether.substrait.ExtendedExpression.expected_type_urls)
  return _internal_expected_type_urls().Get(index);
}
inline std::string* ExtendedExpression::mutable_expected_type_urls(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:skytether.substrait.ExtendedExpression.expected_type_urls)
  return _internal_mutable_expected_type_urls()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ExtendedExpression::set_expected_type_urls(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_expected_type_urls()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:skytether.substrait.ExtendedExpression.expected_type_urls)
}
template <typename Arg_, typename... Args_>
inline void ExtendedExpression::add_expected_type_urls(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_expected_type_urls(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:skytether.substrait.ExtendedExpression.expected_type_urls)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExtendedExpression::expected_type_urls() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skytether.substrait.ExtendedExpression.expected_type_urls)
  return _internal_expected_type_urls();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExtendedExpression::mutable_expected_type_urls() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skytether.substrait.ExtendedExpression.expected_type_urls)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_expected_type_urls();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExtendedExpression::_internal_expected_type_urls() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.expected_type_urls_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExtendedExpression::_internal_mutable_expected_type_urls() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.expected_type_urls_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace substrait
}  // namespace skytether


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_skytether_2fsubstrait_2fextended_5fexpression_2eproto_2epb_2eh
