// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skyproto/mohair/topology.proto
// Protobuf C++ Version: 5.29.3

#include "skyproto/mohair/topology.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace skyproto {
namespace mohair {

inline constexpr MemorySpec::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        count_mebibytes_{0u},
        memory_type_{static_cast< ::skyproto::mohair::MemorySpec_MemoryType >(0)},
        memory_freq_{0u},
        count_channels_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR MemorySpec::MemorySpec(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MemorySpecDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MemorySpecDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MemorySpecDefaultTypeInternal() {}
  union {
    MemorySpec _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MemorySpecDefaultTypeInternal _MemorySpec_default_instance_;

inline constexpr CpuSpec::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        core_freqs_{},
        cache_sizes_{},
        _cache_sizes_cached_byte_size_{0},
        count_threads_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR CpuSpec::CpuSpec(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CpuSpecDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CpuSpecDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CpuSpecDefaultTypeInternal() {}
  union {
    CpuSpec _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CpuSpecDefaultTypeInternal _CpuSpec_default_instance_;

inline constexpr PlatformSpec::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : cpu_info_{},
        mem_info_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PlatformSpec::PlatformSpec(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlatformSpecDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlatformSpecDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlatformSpecDefaultTypeInternal() {}
  union {
    PlatformSpec _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlatformSpecDefaultTypeInternal _PlatformSpec_default_instance_;

inline constexpr ServiceConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        downstream_{},
        label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        location_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        service_platform_{nullptr},
        is_active_{false},
        decompose_alg_{static_cast< ::skyproto::mohair::DecomposeAlg >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR ServiceConfig::ServiceConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ServiceConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServiceConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServiceConfigDefaultTypeInternal() {}
  union {
    ServiceConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServiceConfigDefaultTypeInternal _ServiceConfig_default_instance_;
}  // namespace mohair
}  // namespace skyproto
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_skyproto_2fmohair_2ftopology_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_skyproto_2fmohair_2ftopology_2eproto = nullptr;
const ::uint32_t
    TableStruct_skyproto_2fmohair_2ftopology_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::CpuSpec, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::CpuSpec, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::CpuSpec, _impl_.core_freqs_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::CpuSpec, _impl_.cache_sizes_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::CpuSpec, _impl_.count_threads_),
        ~0u,
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::MemorySpec, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::MemorySpec, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::MemorySpec, _impl_.count_mebibytes_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::MemorySpec, _impl_.memory_type_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::MemorySpec, _impl_.memory_freq_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::MemorySpec, _impl_.count_channels_),
        ~0u,
        0,
        1,
        2,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::PlatformSpec, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::PlatformSpec, _impl_.cpu_info_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::PlatformSpec, _impl_.mem_info_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::ServiceConfig, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::ServiceConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::ServiceConfig, _impl_.is_active_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::ServiceConfig, _impl_.label_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::ServiceConfig, _impl_.location_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::ServiceConfig, _impl_.decompose_alg_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::ServiceConfig, _impl_.service_platform_),
        PROTOBUF_FIELD_OFFSET(::skyproto::mohair::ServiceConfig, _impl_.downstream_),
        ~0u,
        ~0u,
        ~0u,
        1,
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::skyproto::mohair::CpuSpec)},
        {14, 26, -1, sizeof(::skyproto::mohair::MemorySpec)},
        {30, -1, -1, sizeof(::skyproto::mohair::PlatformSpec)},
        {40, 54, -1, sizeof(::skyproto::mohair::ServiceConfig)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::skyproto::mohair::_CpuSpec_default_instance_._instance,
    &::skyproto::mohair::_MemorySpec_default_instance_._instance,
    &::skyproto::mohair::_PlatformSpec_default_instance_._instance,
    &::skyproto::mohair::_ServiceConfig_default_instance_._instance,
};
const char descriptor_table_protodef_skyproto_2fmohair_2ftopology_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\036skyproto/mohair/topology.proto\022\017skypro"
    "to.mohair\032\031google/protobuf/any.proto\"\310\001\n"
    "\007CpuSpec\022\035\n\ncore_freqs\030\001 \003(\002R\tcoreFreqs\022"
    "\037\n\013cache_sizes\030\002 \003(\rR\ncacheSizes\022(\n\rcoun"
    "t_threads\030\003 \001(\rH\000R\014countThreads\210\001\001\"A\n\013De"
    "viceClass\022\n\n\006SERVER\020\000\022\t\n\005DRIVE\020\001\022\007\n\003SOC\020"
    "\002\022\t\n\005ARRAY\020\003\022\007\n\003DPU\020\004B\020\n\016_count_threads\""
    "\304\002\n\nMemorySpec\022\'\n\017count_mebibytes\030\001 \001(\rR"
    "\016countMebibytes\022L\n\013memory_type\030\002 \001(\0162&.s"
    "kyproto.mohair.MemorySpec.MemoryTypeH\000R\n"
    "memoryType\210\001\001\022$\n\013memory_freq\030\003 \001(\rH\001R\nme"
    "moryFreq\210\001\001\022*\n\016count_channels\030\004 \001(\rH\002R\rc"
    "ountChannels\210\001\001\":\n\nMemoryType\022\007\n\003DDR\020\000\022\010"
    "\n\004GDDR\020\001\022\007\n\003NVM\020\002\022\007\n\003CXL\020\003\022\007\n\003CAM\020\004B\016\n\014_"
    "memory_typeB\016\n\014_memory_freqB\021\n\017_count_ch"
    "annels\"{\n\014PlatformSpec\0223\n\010cpu_info\030\001 \003(\013"
    "2\030.skyproto.mohair.CpuSpecR\007cpuInfo\0226\n\010m"
    "em_info\030\002 \003(\0132\033.skyproto.mohair.MemorySp"
    "ecR\007memInfo\"\335\002\n\rServiceConfig\022\033\n\tis_acti"
    "ve\030\001 \001(\010R\010isActive\022\024\n\005label\030\002 \001(\tR\005label"
    "\022\032\n\010location\030\003 \001(\tR\010location\022G\n\rdecompos"
    "e_alg\030\004 \001(\0162\035.skyproto.mohair.DecomposeA"
    "lgH\000R\014decomposeAlg\210\001\001\022M\n\020service_platfor"
    "m\030\005 \001(\0132\035.skyproto.mohair.PlatformSpecH\001"
    "R\017servicePlatform\210\001\001\022>\n\ndownstream\030\006 \003(\013"
    "2\036.skyproto.mohair.ServiceConfigR\ndownst"
    "reamB\020\n\016_decompose_algB\023\n\021_service_platf"
    "orm*s\n\014DecomposeAlg\022\010\n\004None\020\000\022\024\n\020LongPip"
    "elineLeaf\020\001\022\024\n\020LongPipelineHead\020\002\022\020\n\014Tal"
    "lJoinLeaf\020\003\022\020\n\014WideJoinHead\020\004\022\t\n\005Eager\020\005"
    "B\201\001\n\023com.skyproto.mohairB\rTopologyProtoP"
    "\001\242\002\003SMX\252\002\017Skyproto.Mohair\312\002\017Skyproto\\Moh"
    "air\342\002\033Skyproto\\Mohair\\GPBMetadata\352\002\020Skyp"
    "roto::Mohairb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_skyproto_2fmohair_2ftopology_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
};
static ::absl::once_flag descriptor_table_skyproto_2fmohair_2ftopology_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_skyproto_2fmohair_2ftopology_2eproto = {
    false,
    false,
    1340,
    descriptor_table_protodef_skyproto_2fmohair_2ftopology_2eproto,
    "skyproto/mohair/topology.proto",
    &descriptor_table_skyproto_2fmohair_2ftopology_2eproto_once,
    descriptor_table_skyproto_2fmohair_2ftopology_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_skyproto_2fmohair_2ftopology_2eproto::offsets,
    file_level_enum_descriptors_skyproto_2fmohair_2ftopology_2eproto,
    file_level_service_descriptors_skyproto_2fmohair_2ftopology_2eproto,
};
namespace skyproto {
namespace mohair {
const ::google::protobuf::EnumDescriptor* CpuSpec_DeviceClass_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_skyproto_2fmohair_2ftopology_2eproto);
  return file_level_enum_descriptors_skyproto_2fmohair_2ftopology_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CpuSpec_DeviceClass_internal_data_[] = {
    327680u, 0u, };
bool CpuSpec_DeviceClass_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr CpuSpec_DeviceClass CpuSpec::SERVER;
constexpr CpuSpec_DeviceClass CpuSpec::DRIVE;
constexpr CpuSpec_DeviceClass CpuSpec::SOC;
constexpr CpuSpec_DeviceClass CpuSpec::ARRAY;
constexpr CpuSpec_DeviceClass CpuSpec::DPU;
constexpr CpuSpec_DeviceClass CpuSpec::DeviceClass_MIN;
constexpr CpuSpec_DeviceClass CpuSpec::DeviceClass_MAX;
constexpr int CpuSpec::DeviceClass_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* MemorySpec_MemoryType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_skyproto_2fmohair_2ftopology_2eproto);
  return file_level_enum_descriptors_skyproto_2fmohair_2ftopology_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t MemorySpec_MemoryType_internal_data_[] = {
    327680u, 0u, };
bool MemorySpec_MemoryType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr MemorySpec_MemoryType MemorySpec::DDR;
constexpr MemorySpec_MemoryType MemorySpec::GDDR;
constexpr MemorySpec_MemoryType MemorySpec::NVM;
constexpr MemorySpec_MemoryType MemorySpec::CXL;
constexpr MemorySpec_MemoryType MemorySpec::CAM;
constexpr MemorySpec_MemoryType MemorySpec::MemoryType_MIN;
constexpr MemorySpec_MemoryType MemorySpec::MemoryType_MAX;
constexpr int MemorySpec::MemoryType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* DecomposeAlg_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_skyproto_2fmohair_2ftopology_2eproto);
  return file_level_enum_descriptors_skyproto_2fmohair_2ftopology_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t DecomposeAlg_internal_data_[] = {
    393216u, 0u, };
bool DecomposeAlg_IsValid(int value) {
  return 0 <= value && value <= 5;
}
// ===================================================================

class CpuSpec::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CpuSpec>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_._has_bits_);
};

CpuSpec::CpuSpec(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:skyproto.mohair.CpuSpec)
}
inline PROTOBUF_NDEBUG_INLINE CpuSpec::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::skyproto::mohair::CpuSpec& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        core_freqs_{visibility, arena, from.core_freqs_},
        cache_sizes_{visibility, arena, from.cache_sizes_},
        _cache_sizes_cached_byte_size_{0} {}

CpuSpec::CpuSpec(
    ::google::protobuf::Arena* arena,
    const CpuSpec& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CpuSpec* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.count_threads_ = from._impl_.count_threads_;

  // @@protoc_insertion_point(copy_constructor:skyproto.mohair.CpuSpec)
}
inline PROTOBUF_NDEBUG_INLINE CpuSpec::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        core_freqs_{visibility, arena},
        cache_sizes_{visibility, arena},
        _cache_sizes_cached_byte_size_{0} {}

inline void CpuSpec::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.count_threads_ = {};
}
CpuSpec::~CpuSpec() {
  // @@protoc_insertion_point(destructor:skyproto.mohair.CpuSpec)
  SharedDtor(*this);
}
inline void CpuSpec::SharedDtor(MessageLite& self) {
  CpuSpec& this_ = static_cast<CpuSpec&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* CpuSpec::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CpuSpec(arena);
}
constexpr auto CpuSpec::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_.core_freqs_) +
          decltype(CpuSpec::_impl_.core_freqs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_.cache_sizes_) +
          decltype(CpuSpec::_impl_.cache_sizes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(CpuSpec), alignof(CpuSpec), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CpuSpec::PlacementNew_,
                                 sizeof(CpuSpec),
                                 alignof(CpuSpec));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CpuSpec::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CpuSpec_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CpuSpec::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CpuSpec>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CpuSpec::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CpuSpec>(), &CpuSpec::ByteSizeLong,
            &CpuSpec::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_._cached_size_),
        false,
    },
    &CpuSpec::kDescriptorMethods,
    &descriptor_table_skyproto_2fmohair_2ftopology_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CpuSpec::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> CpuSpec::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::skyproto::mohair::CpuSpec>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated float core_freqs = 1 [json_name = "coreFreqs"];
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_.core_freqs_)}},
    // repeated uint32 cache_sizes = 2 [json_name = "cacheSizes"];
    {::_pbi::TcParser::FastV32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_.cache_sizes_)}},
    // optional uint32 count_threads = 3 [json_name = "countThreads"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CpuSpec, _impl_.count_threads_), 0>(),
     {24, 0, 0, PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_.count_threads_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float core_freqs = 1 [json_name = "coreFreqs"];
    {PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_.core_freqs_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated uint32 cache_sizes = 2 [json_name = "cacheSizes"];
    {PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_.cache_sizes_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // optional uint32 count_threads = 3 [json_name = "countThreads"];
    {PROTOBUF_FIELD_OFFSET(CpuSpec, _impl_.count_threads_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CpuSpec::Clear() {
// @@protoc_insertion_point(message_clear_start:skyproto.mohair.CpuSpec)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.core_freqs_.Clear();
  _impl_.cache_sizes_.Clear();
  _impl_.count_threads_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CpuSpec::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CpuSpec& this_ = static_cast<const CpuSpec&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CpuSpec::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CpuSpec& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:skyproto.mohair.CpuSpec)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated float core_freqs = 1 [json_name = "coreFreqs"];
          if (this_._internal_core_freqs_size() > 0) {
            target = stream->WriteFixedPacked(1, this_._internal_core_freqs(), target);
          }

          // repeated uint32 cache_sizes = 2 [json_name = "cacheSizes"];
          {
            int byte_size = this_._impl_._cache_sizes_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt32Packed(
                  2, this_._internal_cache_sizes(), byte_size, target);
            }
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional uint32 count_threads = 3 [json_name = "countThreads"];
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_count_threads(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:skyproto.mohair.CpuSpec)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CpuSpec::ByteSizeLong(const MessageLite& base) {
          const CpuSpec& this_ = static_cast<const CpuSpec&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CpuSpec::ByteSizeLong() const {
          const CpuSpec& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:skyproto.mohair.CpuSpec)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated float core_freqs = 1 [json_name = "coreFreqs"];
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_core_freqs_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
            // repeated uint32 cache_sizes = 2 [json_name = "cacheSizes"];
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
                      this_._internal_cache_sizes(), 1,
                      this_._impl_._cache_sizes_cached_byte_size_);
            }
          }
           {
            // optional uint32 count_threads = 3 [json_name = "countThreads"];
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_count_threads());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CpuSpec::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CpuSpec*>(&to_msg);
  auto& from = static_cast<const CpuSpec&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:skyproto.mohair.CpuSpec)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_core_freqs()->MergeFrom(from._internal_core_freqs());
  _this->_internal_mutable_cache_sizes()->MergeFrom(from._internal_cache_sizes());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.count_threads_ = from._impl_.count_threads_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CpuSpec::CopyFrom(const CpuSpec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:skyproto.mohair.CpuSpec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CpuSpec::InternalSwap(CpuSpec* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.core_freqs_.InternalSwap(&other->_impl_.core_freqs_);
  _impl_.cache_sizes_.InternalSwap(&other->_impl_.cache_sizes_);
        swap(_impl_.count_threads_, other->_impl_.count_threads_);
}

::google::protobuf::Metadata CpuSpec::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MemorySpec::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MemorySpec>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_._has_bits_);
};

MemorySpec::MemorySpec(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:skyproto.mohair.MemorySpec)
}
MemorySpec::MemorySpec(
    ::google::protobuf::Arena* arena, const MemorySpec& from)
    : MemorySpec(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MemorySpec::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MemorySpec::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, count_mebibytes_),
           0,
           offsetof(Impl_, count_channels_) -
               offsetof(Impl_, count_mebibytes_) +
               sizeof(Impl_::count_channels_));
}
MemorySpec::~MemorySpec() {
  // @@protoc_insertion_point(destructor:skyproto.mohair.MemorySpec)
  SharedDtor(*this);
}
inline void MemorySpec::SharedDtor(MessageLite& self) {
  MemorySpec& this_ = static_cast<MemorySpec&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* MemorySpec::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MemorySpec(arena);
}
constexpr auto MemorySpec::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MemorySpec),
                                            alignof(MemorySpec));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MemorySpec::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MemorySpec_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MemorySpec::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MemorySpec>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MemorySpec::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MemorySpec>(), &MemorySpec::ByteSizeLong,
            &MemorySpec::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_._cached_size_),
        false,
    },
    &MemorySpec::kDescriptorMethods,
    &descriptor_table_skyproto_2fmohair_2ftopology_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MemorySpec::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> MemorySpec::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::skyproto::mohair::MemorySpec>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint32 count_channels = 4 [json_name = "countChannels"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MemorySpec, _impl_.count_channels_), 2>(),
     {32, 2, 0, PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.count_channels_)}},
    // uint32 count_mebibytes = 1 [json_name = "countMebibytes"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MemorySpec, _impl_.count_mebibytes_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.count_mebibytes_)}},
    // optional .skyproto.mohair.MemorySpec.MemoryType memory_type = 2 [json_name = "memoryType"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MemorySpec, _impl_.memory_type_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.memory_type_)}},
    // optional uint32 memory_freq = 3 [json_name = "memoryFreq"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MemorySpec, _impl_.memory_freq_), 1>(),
     {24, 1, 0, PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.memory_freq_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 count_mebibytes = 1 [json_name = "countMebibytes"];
    {PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.count_mebibytes_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // optional .skyproto.mohair.MemorySpec.MemoryType memory_type = 2 [json_name = "memoryType"];
    {PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.memory_type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional uint32 memory_freq = 3 [json_name = "memoryFreq"];
    {PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.memory_freq_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 count_channels = 4 [json_name = "countChannels"];
    {PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.count_channels_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MemorySpec::Clear() {
// @@protoc_insertion_point(message_clear_start:skyproto.mohair.MemorySpec)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.count_mebibytes_ = 0u;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.memory_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.count_channels_) -
        reinterpret_cast<char*>(&_impl_.memory_type_)) + sizeof(_impl_.count_channels_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MemorySpec::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MemorySpec& this_ = static_cast<const MemorySpec&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MemorySpec::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MemorySpec& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:skyproto.mohair.MemorySpec)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 count_mebibytes = 1 [json_name = "countMebibytes"];
          if (this_._internal_count_mebibytes() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_count_mebibytes(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .skyproto.mohair.MemorySpec.MemoryType memory_type = 2 [json_name = "memoryType"];
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_memory_type(), target);
          }

          // optional uint32 memory_freq = 3 [json_name = "memoryFreq"];
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_memory_freq(), target);
          }

          // optional uint32 count_channels = 4 [json_name = "countChannels"];
          if (cached_has_bits & 0x00000004u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_count_channels(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:skyproto.mohair.MemorySpec)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MemorySpec::ByteSizeLong(const MessageLite& base) {
          const MemorySpec& this_ = static_cast<const MemorySpec&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MemorySpec::ByteSizeLong() const {
          const MemorySpec& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:skyproto.mohair.MemorySpec)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint32 count_mebibytes = 1 [json_name = "countMebibytes"];
            if (this_._internal_count_mebibytes() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_count_mebibytes());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // optional .skyproto.mohair.MemorySpec.MemoryType memory_type = 2 [json_name = "memoryType"];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_memory_type());
            }
            // optional uint32 memory_freq = 3 [json_name = "memoryFreq"];
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_memory_freq());
            }
            // optional uint32 count_channels = 4 [json_name = "countChannels"];
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_count_channels());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MemorySpec::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MemorySpec*>(&to_msg);
  auto& from = static_cast<const MemorySpec&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:skyproto.mohair.MemorySpec)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_count_mebibytes() != 0) {
    _this->_impl_.count_mebibytes_ = from._impl_.count_mebibytes_;
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.memory_type_ = from._impl_.memory_type_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.memory_freq_ = from._impl_.memory_freq_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.count_channels_ = from._impl_.count_channels_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MemorySpec::CopyFrom(const MemorySpec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:skyproto.mohair.MemorySpec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MemorySpec::InternalSwap(MemorySpec* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.count_channels_)
      + sizeof(MemorySpec::_impl_.count_channels_)
      - PROTOBUF_FIELD_OFFSET(MemorySpec, _impl_.count_mebibytes_)>(
          reinterpret_cast<char*>(&_impl_.count_mebibytes_),
          reinterpret_cast<char*>(&other->_impl_.count_mebibytes_));
}

::google::protobuf::Metadata MemorySpec::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PlatformSpec::_Internal {
 public:
};

PlatformSpec::PlatformSpec(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:skyproto.mohair.PlatformSpec)
}
inline PROTOBUF_NDEBUG_INLINE PlatformSpec::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::skyproto::mohair::PlatformSpec& from_msg)
      : cpu_info_{visibility, arena, from.cpu_info_},
        mem_info_{visibility, arena, from.mem_info_},
        _cached_size_{0} {}

PlatformSpec::PlatformSpec(
    ::google::protobuf::Arena* arena,
    const PlatformSpec& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlatformSpec* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:skyproto.mohair.PlatformSpec)
}
inline PROTOBUF_NDEBUG_INLINE PlatformSpec::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : cpu_info_{visibility, arena},
        mem_info_{visibility, arena},
        _cached_size_{0} {}

inline void PlatformSpec::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PlatformSpec::~PlatformSpec() {
  // @@protoc_insertion_point(destructor:skyproto.mohair.PlatformSpec)
  SharedDtor(*this);
}
inline void PlatformSpec::SharedDtor(MessageLite& self) {
  PlatformSpec& this_ = static_cast<PlatformSpec&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PlatformSpec::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PlatformSpec(arena);
}
constexpr auto PlatformSpec::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PlatformSpec, _impl_.cpu_info_) +
          decltype(PlatformSpec::_impl_.cpu_info_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PlatformSpec, _impl_.mem_info_) +
          decltype(PlatformSpec::_impl_.mem_info_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PlatformSpec), alignof(PlatformSpec), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PlatformSpec::PlacementNew_,
                                 sizeof(PlatformSpec),
                                 alignof(PlatformSpec));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PlatformSpec::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PlatformSpec_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PlatformSpec::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PlatformSpec>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PlatformSpec::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PlatformSpec>(), &PlatformSpec::ByteSizeLong,
            &PlatformSpec::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PlatformSpec, _impl_._cached_size_),
        false,
    },
    &PlatformSpec::kDescriptorMethods,
    &descriptor_table_skyproto_2fmohair_2ftopology_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PlatformSpec::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> PlatformSpec::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::skyproto::mohair::PlatformSpec>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .skyproto.mohair.MemorySpec mem_info = 2 [json_name = "memInfo"];
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(PlatformSpec, _impl_.mem_info_)}},
    // repeated .skyproto.mohair.CpuSpec cpu_info = 1 [json_name = "cpuInfo"];
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PlatformSpec, _impl_.cpu_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .skyproto.mohair.CpuSpec cpu_info = 1 [json_name = "cpuInfo"];
    {PROTOBUF_FIELD_OFFSET(PlatformSpec, _impl_.cpu_info_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .skyproto.mohair.MemorySpec mem_info = 2 [json_name = "memInfo"];
    {PROTOBUF_FIELD_OFFSET(PlatformSpec, _impl_.mem_info_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::skyproto::mohair::CpuSpec>()},
    {::_pbi::TcParser::GetTable<::skyproto::mohair::MemorySpec>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void PlatformSpec::Clear() {
// @@protoc_insertion_point(message_clear_start:skyproto.mohair.PlatformSpec)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cpu_info_.Clear();
  _impl_.mem_info_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PlatformSpec::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PlatformSpec& this_ = static_cast<const PlatformSpec&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PlatformSpec::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PlatformSpec& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:skyproto.mohair.PlatformSpec)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .skyproto.mohair.CpuSpec cpu_info = 1 [json_name = "cpuInfo"];
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_cpu_info_size());
               i < n; i++) {
            const auto& repfield = this_._internal_cpu_info().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .skyproto.mohair.MemorySpec mem_info = 2 [json_name = "memInfo"];
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_mem_info_size());
               i < n; i++) {
            const auto& repfield = this_._internal_mem_info().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:skyproto.mohair.PlatformSpec)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PlatformSpec::ByteSizeLong(const MessageLite& base) {
          const PlatformSpec& this_ = static_cast<const PlatformSpec&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PlatformSpec::ByteSizeLong() const {
          const PlatformSpec& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:skyproto.mohair.PlatformSpec)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .skyproto.mohair.CpuSpec cpu_info = 1 [json_name = "cpuInfo"];
            {
              total_size += 1UL * this_._internal_cpu_info_size();
              for (const auto& msg : this_._internal_cpu_info()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .skyproto.mohair.MemorySpec mem_info = 2 [json_name = "memInfo"];
            {
              total_size += 1UL * this_._internal_mem_info_size();
              for (const auto& msg : this_._internal_mem_info()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PlatformSpec::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PlatformSpec*>(&to_msg);
  auto& from = static_cast<const PlatformSpec&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:skyproto.mohair.PlatformSpec)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_cpu_info()->MergeFrom(
      from._internal_cpu_info());
  _this->_internal_mutable_mem_info()->MergeFrom(
      from._internal_mem_info());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PlatformSpec::CopyFrom(const PlatformSpec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:skyproto.mohair.PlatformSpec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlatformSpec::InternalSwap(PlatformSpec* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.cpu_info_.InternalSwap(&other->_impl_.cpu_info_);
  _impl_.mem_info_.InternalSwap(&other->_impl_.mem_info_);
}

::google::protobuf::Metadata PlatformSpec::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ServiceConfig::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ServiceConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_._has_bits_);
};

ServiceConfig::ServiceConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:skyproto.mohair.ServiceConfig)
}
inline PROTOBUF_NDEBUG_INLINE ServiceConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::skyproto::mohair::ServiceConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        downstream_{visibility, arena, from.downstream_},
        label_(arena, from.label_),
        location_(arena, from.location_) {}

ServiceConfig::ServiceConfig(
    ::google::protobuf::Arena* arena,
    const ServiceConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ServiceConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.service_platform_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::skyproto::mohair::PlatformSpec>(
                              arena, *from._impl_.service_platform_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, is_active_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, is_active_),
           offsetof(Impl_, decompose_alg_) -
               offsetof(Impl_, is_active_) +
               sizeof(Impl_::decompose_alg_));

  // @@protoc_insertion_point(copy_constructor:skyproto.mohair.ServiceConfig)
}
inline PROTOBUF_NDEBUG_INLINE ServiceConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        downstream_{visibility, arena},
        label_(arena),
        location_(arena) {}

inline void ServiceConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, service_platform_),
           0,
           offsetof(Impl_, decompose_alg_) -
               offsetof(Impl_, service_platform_) +
               sizeof(Impl_::decompose_alg_));
}
ServiceConfig::~ServiceConfig() {
  // @@protoc_insertion_point(destructor:skyproto.mohair.ServiceConfig)
  SharedDtor(*this);
}
inline void ServiceConfig::SharedDtor(MessageLite& self) {
  ServiceConfig& this_ = static_cast<ServiceConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.label_.Destroy();
  this_._impl_.location_.Destroy();
  delete this_._impl_.service_platform_;
  this_._impl_.~Impl_();
}

inline void* ServiceConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ServiceConfig(arena);
}
constexpr auto ServiceConfig::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.downstream_) +
          decltype(ServiceConfig::_impl_.downstream_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ServiceConfig), alignof(ServiceConfig), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ServiceConfig::PlacementNew_,
                                 sizeof(ServiceConfig),
                                 alignof(ServiceConfig));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ServiceConfig::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ServiceConfig_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ServiceConfig::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ServiceConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ServiceConfig::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ServiceConfig>(), &ServiceConfig::ByteSizeLong,
            &ServiceConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_._cached_size_),
        false,
    },
    &ServiceConfig::kDescriptorMethods,
    &descriptor_table_skyproto_2fmohair_2ftopology_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ServiceConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 51, 2> ServiceConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::skyproto::mohair::ServiceConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool is_active = 1 [json_name = "isActive"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ServiceConfig, _impl_.is_active_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.is_active_)}},
    // string label = 2 [json_name = "label"];
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.label_)}},
    // string location = 3 [json_name = "location"];
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.location_)}},
    // optional .skyproto.mohair.DecomposeAlg decompose_alg = 4 [json_name = "decomposeAlg"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServiceConfig, _impl_.decompose_alg_), 1>(),
     {32, 1, 0, PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.decompose_alg_)}},
    // optional .skyproto.mohair.PlatformSpec service_platform = 5 [json_name = "servicePlatform"];
    {::_pbi::TcParser::FastMtS1,
     {42, 0, 0, PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.service_platform_)}},
    // repeated .skyproto.mohair.ServiceConfig downstream = 6 [json_name = "downstream"];
    {::_pbi::TcParser::FastMtR1,
     {50, 63, 1, PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.downstream_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_active = 1 [json_name = "isActive"];
    {PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.is_active_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string label = 2 [json_name = "label"];
    {PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.label_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string location = 3 [json_name = "location"];
    {PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.location_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .skyproto.mohair.DecomposeAlg decompose_alg = 4 [json_name = "decomposeAlg"];
    {PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.decompose_alg_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional .skyproto.mohair.PlatformSpec service_platform = 5 [json_name = "servicePlatform"];
    {PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.service_platform_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .skyproto.mohair.ServiceConfig downstream = 6 [json_name = "downstream"];
    {PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.downstream_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::skyproto::mohair::PlatformSpec>()},
    {::_pbi::TcParser::GetTable<::skyproto::mohair::ServiceConfig>()},
  }}, {{
    "\35\0\5\10\0\0\0\0"
    "skyproto.mohair.ServiceConfig"
    "label"
    "location"
  }},
};

PROTOBUF_NOINLINE void ServiceConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:skyproto.mohair.ServiceConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.downstream_.Clear();
  _impl_.label_.ClearToEmpty();
  _impl_.location_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.service_platform_ != nullptr);
    _impl_.service_platform_->Clear();
  }
  _impl_.is_active_ = false;
  _impl_.decompose_alg_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ServiceConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ServiceConfig& this_ = static_cast<const ServiceConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ServiceConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ServiceConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:skyproto.mohair.ServiceConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool is_active = 1 [json_name = "isActive"];
          if (this_._internal_is_active() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_is_active(), target);
          }

          // string label = 2 [json_name = "label"];
          if (!this_._internal_label().empty()) {
            const std::string& _s = this_._internal_label();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "skyproto.mohair.ServiceConfig.label");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string location = 3 [json_name = "location"];
          if (!this_._internal_location().empty()) {
            const std::string& _s = this_._internal_location();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "skyproto.mohair.ServiceConfig.location");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .skyproto.mohair.DecomposeAlg decompose_alg = 4 [json_name = "decomposeAlg"];
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                4, this_._internal_decompose_alg(), target);
          }

          // optional .skyproto.mohair.PlatformSpec service_platform = 5 [json_name = "servicePlatform"];
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                5, *this_._impl_.service_platform_, this_._impl_.service_platform_->GetCachedSize(), target,
                stream);
          }

          // repeated .skyproto.mohair.ServiceConfig downstream = 6 [json_name = "downstream"];
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_downstream_size());
               i < n; i++) {
            const auto& repfield = this_._internal_downstream().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    6, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:skyproto.mohair.ServiceConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ServiceConfig::ByteSizeLong(const MessageLite& base) {
          const ServiceConfig& this_ = static_cast<const ServiceConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ServiceConfig::ByteSizeLong() const {
          const ServiceConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:skyproto.mohair.ServiceConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .skyproto.mohair.ServiceConfig downstream = 6 [json_name = "downstream"];
            {
              total_size += 1UL * this_._internal_downstream_size();
              for (const auto& msg : this_._internal_downstream()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string label = 2 [json_name = "label"];
            if (!this_._internal_label().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_label());
            }
            // string location = 3 [json_name = "location"];
            if (!this_._internal_location().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_location());
            }
          }
           {
            // optional .skyproto.mohair.PlatformSpec service_platform = 5 [json_name = "servicePlatform"];
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.service_platform_);
            }
          }
           {
            // bool is_active = 1 [json_name = "isActive"];
            if (this_._internal_is_active() != 0) {
              total_size += 2;
            }
          }
           {
            // optional .skyproto.mohair.DecomposeAlg decompose_alg = 4 [json_name = "decomposeAlg"];
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_decompose_alg());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ServiceConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ServiceConfig*>(&to_msg);
  auto& from = static_cast<const ServiceConfig&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:skyproto.mohair.ServiceConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_downstream()->MergeFrom(
      from._internal_downstream());
  if (!from._internal_label().empty()) {
    _this->_internal_set_label(from._internal_label());
  }
  if (!from._internal_location().empty()) {
    _this->_internal_set_location(from._internal_location());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.service_platform_ != nullptr);
    if (_this->_impl_.service_platform_ == nullptr) {
      _this->_impl_.service_platform_ =
          ::google::protobuf::Message::CopyConstruct<::skyproto::mohair::PlatformSpec>(arena, *from._impl_.service_platform_);
    } else {
      _this->_impl_.service_platform_->MergeFrom(*from._impl_.service_platform_);
    }
  }
  if (from._internal_is_active() != 0) {
    _this->_impl_.is_active_ = from._impl_.is_active_;
  }
  if (cached_has_bits & 0x00000002u) {
    _this->_impl_.decompose_alg_ = from._impl_.decompose_alg_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServiceConfig::CopyFrom(const ServiceConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:skyproto.mohair.ServiceConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ServiceConfig::InternalSwap(ServiceConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.downstream_.InternalSwap(&other->_impl_.downstream_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.label_, &other->_impl_.label_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.location_, &other->_impl_.location_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.decompose_alg_)
      + sizeof(ServiceConfig::_impl_.decompose_alg_)
      - PROTOBUF_FIELD_OFFSET(ServiceConfig, _impl_.service_platform_)>(
          reinterpret_cast<char*>(&_impl_.service_platform_),
          reinterpret_cast<char*>(&other->_impl_.service_platform_));
}

::google::protobuf::Metadata ServiceConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace mohair
}  // namespace skyproto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_skyproto_2fmohair_2ftopology_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
