// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skyproto/mohair/topology.proto
// Protobuf C++ Version: 5.29.3

#ifndef skyproto_2fmohair_2ftopology_2eproto_2epb_2eh
#define skyproto_2fmohair_2ftopology_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/any.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_skyproto_2fmohair_2ftopology_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_skyproto_2fmohair_2ftopology_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_skyproto_2fmohair_2ftopology_2eproto;
namespace skyproto {
namespace mohair {
class CpuSpec;
struct CpuSpecDefaultTypeInternal;
extern CpuSpecDefaultTypeInternal _CpuSpec_default_instance_;
class MemorySpec;
struct MemorySpecDefaultTypeInternal;
extern MemorySpecDefaultTypeInternal _MemorySpec_default_instance_;
class PlatformSpec;
struct PlatformSpecDefaultTypeInternal;
extern PlatformSpecDefaultTypeInternal _PlatformSpec_default_instance_;
class ServiceConfig;
struct ServiceConfigDefaultTypeInternal;
extern ServiceConfigDefaultTypeInternal _ServiceConfig_default_instance_;
}  // namespace mohair
}  // namespace skyproto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace skyproto {
namespace mohair {
enum CpuSpec_DeviceClass : int {
  CpuSpec_DeviceClass_SERVER = 0,
  CpuSpec_DeviceClass_DRIVE = 1,
  CpuSpec_DeviceClass_SOC = 2,
  CpuSpec_DeviceClass_ARRAY = 3,
  CpuSpec_DeviceClass_DPU = 4,
  CpuSpec_DeviceClass_CpuSpec_DeviceClass_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  CpuSpec_DeviceClass_CpuSpec_DeviceClass_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool CpuSpec_DeviceClass_IsValid(int value);
extern const uint32_t CpuSpec_DeviceClass_internal_data_[];
constexpr CpuSpec_DeviceClass CpuSpec_DeviceClass_DeviceClass_MIN = static_cast<CpuSpec_DeviceClass>(0);
constexpr CpuSpec_DeviceClass CpuSpec_DeviceClass_DeviceClass_MAX = static_cast<CpuSpec_DeviceClass>(4);
constexpr int CpuSpec_DeviceClass_DeviceClass_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
CpuSpec_DeviceClass_descriptor();
template <typename T>
const std::string& CpuSpec_DeviceClass_Name(T value) {
  static_assert(std::is_same<T, CpuSpec_DeviceClass>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DeviceClass_Name().");
  return CpuSpec_DeviceClass_Name(static_cast<CpuSpec_DeviceClass>(value));
}
template <>
inline const std::string& CpuSpec_DeviceClass_Name(CpuSpec_DeviceClass value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CpuSpec_DeviceClass_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool CpuSpec_DeviceClass_Parse(absl::string_view name, CpuSpec_DeviceClass* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CpuSpec_DeviceClass>(
      CpuSpec_DeviceClass_descriptor(), name, value);
}
enum MemorySpec_MemoryType : int {
  MemorySpec_MemoryType_DDR = 0,
  MemorySpec_MemoryType_GDDR = 1,
  MemorySpec_MemoryType_NVM = 2,
  MemorySpec_MemoryType_CXL = 3,
  MemorySpec_MemoryType_CAM = 4,
  MemorySpec_MemoryType_MemorySpec_MemoryType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MemorySpec_MemoryType_MemorySpec_MemoryType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MemorySpec_MemoryType_IsValid(int value);
extern const uint32_t MemorySpec_MemoryType_internal_data_[];
constexpr MemorySpec_MemoryType MemorySpec_MemoryType_MemoryType_MIN = static_cast<MemorySpec_MemoryType>(0);
constexpr MemorySpec_MemoryType MemorySpec_MemoryType_MemoryType_MAX = static_cast<MemorySpec_MemoryType>(4);
constexpr int MemorySpec_MemoryType_MemoryType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
MemorySpec_MemoryType_descriptor();
template <typename T>
const std::string& MemorySpec_MemoryType_Name(T value) {
  static_assert(std::is_same<T, MemorySpec_MemoryType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MemoryType_Name().");
  return MemorySpec_MemoryType_Name(static_cast<MemorySpec_MemoryType>(value));
}
template <>
inline const std::string& MemorySpec_MemoryType_Name(MemorySpec_MemoryType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MemorySpec_MemoryType_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool MemorySpec_MemoryType_Parse(absl::string_view name, MemorySpec_MemoryType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MemorySpec_MemoryType>(
      MemorySpec_MemoryType_descriptor(), name, value);
}
enum DecomposeAlg : int {
  None = 0,
  LongPipelineLeaf = 1,
  LongPipelineHead = 2,
  TallJoinLeaf = 3,
  WideJoinHead = 4,
  Eager = 5,
  DecomposeAlg_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DecomposeAlg_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DecomposeAlg_IsValid(int value);
extern const uint32_t DecomposeAlg_internal_data_[];
constexpr DecomposeAlg DecomposeAlg_MIN = static_cast<DecomposeAlg>(0);
constexpr DecomposeAlg DecomposeAlg_MAX = static_cast<DecomposeAlg>(5);
constexpr int DecomposeAlg_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor*
DecomposeAlg_descriptor();
template <typename T>
const std::string& DecomposeAlg_Name(T value) {
  static_assert(std::is_same<T, DecomposeAlg>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DecomposeAlg_Name().");
  return DecomposeAlg_Name(static_cast<DecomposeAlg>(value));
}
template <>
inline const std::string& DecomposeAlg_Name(DecomposeAlg value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DecomposeAlg_descriptor,
                                                 0, 5>(
      static_cast<int>(value));
}
inline bool DecomposeAlg_Parse(absl::string_view name, DecomposeAlg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DecomposeAlg>(
      DecomposeAlg_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class MemorySpec final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:skyproto.mohair.MemorySpec) */ {
 public:
  inline MemorySpec() : MemorySpec(nullptr) {}
  ~MemorySpec() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MemorySpec* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MemorySpec));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MemorySpec(
      ::google::protobuf::internal::ConstantInitialized);

  inline MemorySpec(const MemorySpec& from) : MemorySpec(nullptr, from) {}
  inline MemorySpec(MemorySpec&& from) noexcept
      : MemorySpec(nullptr, std::move(from)) {}
  inline MemorySpec& operator=(const MemorySpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline MemorySpec& operator=(MemorySpec&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MemorySpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const MemorySpec* internal_default_instance() {
    return reinterpret_cast<const MemorySpec*>(
        &_MemorySpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MemorySpec& a, MemorySpec& b) { a.Swap(&b); }
  inline void Swap(MemorySpec* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MemorySpec* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MemorySpec* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MemorySpec>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MemorySpec& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MemorySpec& from) { MemorySpec::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MemorySpec* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "skyproto.mohair.MemorySpec"; }

 protected:
  explicit MemorySpec(::google::protobuf::Arena* arena);
  MemorySpec(::google::protobuf::Arena* arena, const MemorySpec& from);
  MemorySpec(::google::protobuf::Arena* arena, MemorySpec&& from) noexcept
      : MemorySpec(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using MemoryType = MemorySpec_MemoryType;
  static constexpr MemoryType DDR = MemorySpec_MemoryType_DDR;
  static constexpr MemoryType GDDR = MemorySpec_MemoryType_GDDR;
  static constexpr MemoryType NVM = MemorySpec_MemoryType_NVM;
  static constexpr MemoryType CXL = MemorySpec_MemoryType_CXL;
  static constexpr MemoryType CAM = MemorySpec_MemoryType_CAM;
  static inline bool MemoryType_IsValid(int value) {
    return MemorySpec_MemoryType_IsValid(value);
  }
  static constexpr MemoryType MemoryType_MIN = MemorySpec_MemoryType_MemoryType_MIN;
  static constexpr MemoryType MemoryType_MAX = MemorySpec_MemoryType_MemoryType_MAX;
  static constexpr int MemoryType_ARRAYSIZE = MemorySpec_MemoryType_MemoryType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* MemoryType_descriptor() {
    return MemorySpec_MemoryType_descriptor();
  }
  template <typename T>
  static inline const std::string& MemoryType_Name(T value) {
    return MemorySpec_MemoryType_Name(value);
  }
  static inline bool MemoryType_Parse(absl::string_view name, MemoryType* value) {
    return MemorySpec_MemoryType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kCountMebibytesFieldNumber = 1,
    kMemoryTypeFieldNumber = 2,
    kMemoryFreqFieldNumber = 3,
    kCountChannelsFieldNumber = 4,
  };
  // uint32 count_mebibytes = 1 [json_name = "countMebibytes"];
  void clear_count_mebibytes() ;
  ::uint32_t count_mebibytes() const;
  void set_count_mebibytes(::uint32_t value);

  private:
  ::uint32_t _internal_count_mebibytes() const;
  void _internal_set_count_mebibytes(::uint32_t value);

  public:
  // optional .skyproto.mohair.MemorySpec.MemoryType memory_type = 2 [json_name = "memoryType"];
  bool has_memory_type() const;
  void clear_memory_type() ;
  ::skyproto::mohair::MemorySpec_MemoryType memory_type() const;
  void set_memory_type(::skyproto::mohair::MemorySpec_MemoryType value);

  private:
  ::skyproto::mohair::MemorySpec_MemoryType _internal_memory_type() const;
  void _internal_set_memory_type(::skyproto::mohair::MemorySpec_MemoryType value);

  public:
  // optional uint32 memory_freq = 3 [json_name = "memoryFreq"];
  bool has_memory_freq() const;
  void clear_memory_freq() ;
  ::uint32_t memory_freq() const;
  void set_memory_freq(::uint32_t value);

  private:
  ::uint32_t _internal_memory_freq() const;
  void _internal_set_memory_freq(::uint32_t value);

  public:
  // optional uint32 count_channels = 4 [json_name = "countChannels"];
  bool has_count_channels() const;
  void clear_count_channels() ;
  ::uint32_t count_channels() const;
  void set_count_channels(::uint32_t value);

  private:
  ::uint32_t _internal_count_channels() const;
  void _internal_set_count_channels(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:skyproto.mohair.MemorySpec)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MemorySpec& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t count_mebibytes_;
    int memory_type_;
    ::uint32_t memory_freq_;
    ::uint32_t count_channels_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_skyproto_2fmohair_2ftopology_2eproto;
};
// -------------------------------------------------------------------

class CpuSpec final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:skyproto.mohair.CpuSpec) */ {
 public:
  inline CpuSpec() : CpuSpec(nullptr) {}
  ~CpuSpec() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CpuSpec* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CpuSpec));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CpuSpec(
      ::google::protobuf::internal::ConstantInitialized);

  inline CpuSpec(const CpuSpec& from) : CpuSpec(nullptr, from) {}
  inline CpuSpec(CpuSpec&& from) noexcept
      : CpuSpec(nullptr, std::move(from)) {}
  inline CpuSpec& operator=(const CpuSpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline CpuSpec& operator=(CpuSpec&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CpuSpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const CpuSpec* internal_default_instance() {
    return reinterpret_cast<const CpuSpec*>(
        &_CpuSpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CpuSpec& a, CpuSpec& b) { a.Swap(&b); }
  inline void Swap(CpuSpec* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CpuSpec* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CpuSpec* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CpuSpec>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CpuSpec& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CpuSpec& from) { CpuSpec::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CpuSpec* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "skyproto.mohair.CpuSpec"; }

 protected:
  explicit CpuSpec(::google::protobuf::Arena* arena);
  CpuSpec(::google::protobuf::Arena* arena, const CpuSpec& from);
  CpuSpec(::google::protobuf::Arena* arena, CpuSpec&& from) noexcept
      : CpuSpec(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using DeviceClass = CpuSpec_DeviceClass;
  static constexpr DeviceClass SERVER = CpuSpec_DeviceClass_SERVER;
  static constexpr DeviceClass DRIVE = CpuSpec_DeviceClass_DRIVE;
  static constexpr DeviceClass SOC = CpuSpec_DeviceClass_SOC;
  static constexpr DeviceClass ARRAY = CpuSpec_DeviceClass_ARRAY;
  static constexpr DeviceClass DPU = CpuSpec_DeviceClass_DPU;
  static inline bool DeviceClass_IsValid(int value) {
    return CpuSpec_DeviceClass_IsValid(value);
  }
  static constexpr DeviceClass DeviceClass_MIN = CpuSpec_DeviceClass_DeviceClass_MIN;
  static constexpr DeviceClass DeviceClass_MAX = CpuSpec_DeviceClass_DeviceClass_MAX;
  static constexpr int DeviceClass_ARRAYSIZE = CpuSpec_DeviceClass_DeviceClass_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* DeviceClass_descriptor() {
    return CpuSpec_DeviceClass_descriptor();
  }
  template <typename T>
  static inline const std::string& DeviceClass_Name(T value) {
    return CpuSpec_DeviceClass_Name(value);
  }
  static inline bool DeviceClass_Parse(absl::string_view name, DeviceClass* value) {
    return CpuSpec_DeviceClass_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kCoreFreqsFieldNumber = 1,
    kCacheSizesFieldNumber = 2,
    kCountThreadsFieldNumber = 3,
  };
  // repeated float core_freqs = 1 [json_name = "coreFreqs"];
  int core_freqs_size() const;
  private:
  int _internal_core_freqs_size() const;

  public:
  void clear_core_freqs() ;
  float core_freqs(int index) const;
  void set_core_freqs(int index, float value);
  void add_core_freqs(float value);
  const ::google::protobuf::RepeatedField<float>& core_freqs() const;
  ::google::protobuf::RepeatedField<float>* mutable_core_freqs();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_core_freqs() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_core_freqs();

  public:
  // repeated uint32 cache_sizes = 2 [json_name = "cacheSizes"];
  int cache_sizes_size() const;
  private:
  int _internal_cache_sizes_size() const;

  public:
  void clear_cache_sizes() ;
  ::uint32_t cache_sizes(int index) const;
  void set_cache_sizes(int index, ::uint32_t value);
  void add_cache_sizes(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& cache_sizes() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_cache_sizes();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_cache_sizes() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_cache_sizes();

  public:
  // optional uint32 count_threads = 3 [json_name = "countThreads"];
  bool has_count_threads() const;
  void clear_count_threads() ;
  ::uint32_t count_threads() const;
  void set_count_threads(::uint32_t value);

  private:
  ::uint32_t _internal_count_threads() const;
  void _internal_set_count_threads(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:skyproto.mohair.CpuSpec)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CpuSpec& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> core_freqs_;
    ::google::protobuf::RepeatedField<::uint32_t> cache_sizes_;
    ::google::protobuf::internal::CachedSize _cache_sizes_cached_byte_size_;
    ::uint32_t count_threads_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_skyproto_2fmohair_2ftopology_2eproto;
};
// -------------------------------------------------------------------

class PlatformSpec final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:skyproto.mohair.PlatformSpec) */ {
 public:
  inline PlatformSpec() : PlatformSpec(nullptr) {}
  ~PlatformSpec() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlatformSpec* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlatformSpec));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlatformSpec(
      ::google::protobuf::internal::ConstantInitialized);

  inline PlatformSpec(const PlatformSpec& from) : PlatformSpec(nullptr, from) {}
  inline PlatformSpec(PlatformSpec&& from) noexcept
      : PlatformSpec(nullptr, std::move(from)) {}
  inline PlatformSpec& operator=(const PlatformSpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlatformSpec& operator=(PlatformSpec&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlatformSpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlatformSpec* internal_default_instance() {
    return reinterpret_cast<const PlatformSpec*>(
        &_PlatformSpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PlatformSpec& a, PlatformSpec& b) { a.Swap(&b); }
  inline void Swap(PlatformSpec* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlatformSpec* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlatformSpec* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlatformSpec>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlatformSpec& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlatformSpec& from) { PlatformSpec::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlatformSpec* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "skyproto.mohair.PlatformSpec"; }

 protected:
  explicit PlatformSpec(::google::protobuf::Arena* arena);
  PlatformSpec(::google::protobuf::Arena* arena, const PlatformSpec& from);
  PlatformSpec(::google::protobuf::Arena* arena, PlatformSpec&& from) noexcept
      : PlatformSpec(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCpuInfoFieldNumber = 1,
    kMemInfoFieldNumber = 2,
  };
  // repeated .skyproto.mohair.CpuSpec cpu_info = 1 [json_name = "cpuInfo"];
  int cpu_info_size() const;
  private:
  int _internal_cpu_info_size() const;

  public:
  void clear_cpu_info() ;
  ::skyproto::mohair::CpuSpec* mutable_cpu_info(int index);
  ::google::protobuf::RepeatedPtrField<::skyproto::mohair::CpuSpec>* mutable_cpu_info();

  private:
  const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::CpuSpec>& _internal_cpu_info() const;
  ::google::protobuf::RepeatedPtrField<::skyproto::mohair::CpuSpec>* _internal_mutable_cpu_info();
  public:
  const ::skyproto::mohair::CpuSpec& cpu_info(int index) const;
  ::skyproto::mohair::CpuSpec* add_cpu_info();
  const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::CpuSpec>& cpu_info() const;
  // repeated .skyproto.mohair.MemorySpec mem_info = 2 [json_name = "memInfo"];
  int mem_info_size() const;
  private:
  int _internal_mem_info_size() const;

  public:
  void clear_mem_info() ;
  ::skyproto::mohair::MemorySpec* mutable_mem_info(int index);
  ::google::protobuf::RepeatedPtrField<::skyproto::mohair::MemorySpec>* mutable_mem_info();

  private:
  const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::MemorySpec>& _internal_mem_info() const;
  ::google::protobuf::RepeatedPtrField<::skyproto::mohair::MemorySpec>* _internal_mutable_mem_info();
  public:
  const ::skyproto::mohair::MemorySpec& mem_info(int index) const;
  ::skyproto::mohair::MemorySpec* add_mem_info();
  const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::MemorySpec>& mem_info() const;
  // @@protoc_insertion_point(class_scope:skyproto.mohair.PlatformSpec)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PlatformSpec& from_msg);
    ::google::protobuf::RepeatedPtrField< ::skyproto::mohair::CpuSpec > cpu_info_;
    ::google::protobuf::RepeatedPtrField< ::skyproto::mohair::MemorySpec > mem_info_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_skyproto_2fmohair_2ftopology_2eproto;
};
// -------------------------------------------------------------------

class ServiceConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:skyproto.mohair.ServiceConfig) */ {
 public:
  inline ServiceConfig() : ServiceConfig(nullptr) {}
  ~ServiceConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ServiceConfig* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ServiceConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ServiceConfig(
      ::google::protobuf::internal::ConstantInitialized);

  inline ServiceConfig(const ServiceConfig& from) : ServiceConfig(nullptr, from) {}
  inline ServiceConfig(ServiceConfig&& from) noexcept
      : ServiceConfig(nullptr, std::move(from)) {}
  inline ServiceConfig& operator=(const ServiceConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServiceConfig& operator=(ServiceConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServiceConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServiceConfig* internal_default_instance() {
    return reinterpret_cast<const ServiceConfig*>(
        &_ServiceConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ServiceConfig& a, ServiceConfig& b) { a.Swap(&b); }
  inline void Swap(ServiceConfig* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServiceConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServiceConfig* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ServiceConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ServiceConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ServiceConfig& from) { ServiceConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ServiceConfig* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "skyproto.mohair.ServiceConfig"; }

 protected:
  explicit ServiceConfig(::google::protobuf::Arena* arena);
  ServiceConfig(::google::protobuf::Arena* arena, const ServiceConfig& from);
  ServiceConfig(::google::protobuf::Arena* arena, ServiceConfig&& from) noexcept
      : ServiceConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDownstreamFieldNumber = 6,
    kLabelFieldNumber = 2,
    kLocationFieldNumber = 3,
    kServicePlatformFieldNumber = 5,
    kIsActiveFieldNumber = 1,
    kDecomposeAlgFieldNumber = 4,
  };
  // repeated .skyproto.mohair.ServiceConfig downstream = 6 [json_name = "downstream"];
  int downstream_size() const;
  private:
  int _internal_downstream_size() const;

  public:
  void clear_downstream() ;
  ::skyproto::mohair::ServiceConfig* mutable_downstream(int index);
  ::google::protobuf::RepeatedPtrField<::skyproto::mohair::ServiceConfig>* mutable_downstream();

  private:
  const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::ServiceConfig>& _internal_downstream() const;
  ::google::protobuf::RepeatedPtrField<::skyproto::mohair::ServiceConfig>* _internal_mutable_downstream();
  public:
  const ::skyproto::mohair::ServiceConfig& downstream(int index) const;
  ::skyproto::mohair::ServiceConfig* add_downstream();
  const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::ServiceConfig>& downstream() const;
  // string label = 2 [json_name = "label"];
  void clear_label() ;
  const std::string& label() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_label(Arg_&& arg, Args_... args);
  std::string* mutable_label();
  PROTOBUF_NODISCARD std::string* release_label();
  void set_allocated_label(std::string* value);

  private:
  const std::string& _internal_label() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_label(
      const std::string& value);
  std::string* _internal_mutable_label();

  public:
  // string location = 3 [json_name = "location"];
  void clear_location() ;
  const std::string& location() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_location(Arg_&& arg, Args_... args);
  std::string* mutable_location();
  PROTOBUF_NODISCARD std::string* release_location();
  void set_allocated_location(std::string* value);

  private:
  const std::string& _internal_location() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_location(
      const std::string& value);
  std::string* _internal_mutable_location();

  public:
  // optional .skyproto.mohair.PlatformSpec service_platform = 5 [json_name = "servicePlatform"];
  bool has_service_platform() const;
  void clear_service_platform() ;
  const ::skyproto::mohair::PlatformSpec& service_platform() const;
  PROTOBUF_NODISCARD ::skyproto::mohair::PlatformSpec* release_service_platform();
  ::skyproto::mohair::PlatformSpec* mutable_service_platform();
  void set_allocated_service_platform(::skyproto::mohair::PlatformSpec* value);
  void unsafe_arena_set_allocated_service_platform(::skyproto::mohair::PlatformSpec* value);
  ::skyproto::mohair::PlatformSpec* unsafe_arena_release_service_platform();

  private:
  const ::skyproto::mohair::PlatformSpec& _internal_service_platform() const;
  ::skyproto::mohair::PlatformSpec* _internal_mutable_service_platform();

  public:
  // bool is_active = 1 [json_name = "isActive"];
  void clear_is_active() ;
  bool is_active() const;
  void set_is_active(bool value);

  private:
  bool _internal_is_active() const;
  void _internal_set_is_active(bool value);

  public:
  // optional .skyproto.mohair.DecomposeAlg decompose_alg = 4 [json_name = "decomposeAlg"];
  bool has_decompose_alg() const;
  void clear_decompose_alg() ;
  ::skyproto::mohair::DecomposeAlg decompose_alg() const;
  void set_decompose_alg(::skyproto::mohair::DecomposeAlg value);

  private:
  ::skyproto::mohair::DecomposeAlg _internal_decompose_alg() const;
  void _internal_set_decompose_alg(::skyproto::mohair::DecomposeAlg value);

  public:
  // @@protoc_insertion_point(class_scope:skyproto.mohair.ServiceConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 2,
      51, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ServiceConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::skyproto::mohair::ServiceConfig > downstream_;
    ::google::protobuf::internal::ArenaStringPtr label_;
    ::google::protobuf::internal::ArenaStringPtr location_;
    ::skyproto::mohair::PlatformSpec* service_platform_;
    bool is_active_;
    int decompose_alg_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_skyproto_2fmohair_2ftopology_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CpuSpec

// repeated float core_freqs = 1 [json_name = "coreFreqs"];
inline int CpuSpec::_internal_core_freqs_size() const {
  return _internal_core_freqs().size();
}
inline int CpuSpec::core_freqs_size() const {
  return _internal_core_freqs_size();
}
inline void CpuSpec::clear_core_freqs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.core_freqs_.Clear();
}
inline float CpuSpec::core_freqs(int index) const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.CpuSpec.core_freqs)
  return _internal_core_freqs().Get(index);
}
inline void CpuSpec::set_core_freqs(int index, float value) {
  _internal_mutable_core_freqs()->Set(index, value);
  // @@protoc_insertion_point(field_set:skyproto.mohair.CpuSpec.core_freqs)
}
inline void CpuSpec::add_core_freqs(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_core_freqs()->Add(value);
  // @@protoc_insertion_point(field_add:skyproto.mohair.CpuSpec.core_freqs)
}
inline const ::google::protobuf::RepeatedField<float>& CpuSpec::core_freqs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skyproto.mohair.CpuSpec.core_freqs)
  return _internal_core_freqs();
}
inline ::google::protobuf::RepeatedField<float>* CpuSpec::mutable_core_freqs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skyproto.mohair.CpuSpec.core_freqs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_core_freqs();
}
inline const ::google::protobuf::RepeatedField<float>&
CpuSpec::_internal_core_freqs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.core_freqs_;
}
inline ::google::protobuf::RepeatedField<float>* CpuSpec::_internal_mutable_core_freqs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.core_freqs_;
}

// repeated uint32 cache_sizes = 2 [json_name = "cacheSizes"];
inline int CpuSpec::_internal_cache_sizes_size() const {
  return _internal_cache_sizes().size();
}
inline int CpuSpec::cache_sizes_size() const {
  return _internal_cache_sizes_size();
}
inline void CpuSpec::clear_cache_sizes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_sizes_.Clear();
}
inline ::uint32_t CpuSpec::cache_sizes(int index) const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.CpuSpec.cache_sizes)
  return _internal_cache_sizes().Get(index);
}
inline void CpuSpec::set_cache_sizes(int index, ::uint32_t value) {
  _internal_mutable_cache_sizes()->Set(index, value);
  // @@protoc_insertion_point(field_set:skyproto.mohair.CpuSpec.cache_sizes)
}
inline void CpuSpec::add_cache_sizes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_cache_sizes()->Add(value);
  // @@protoc_insertion_point(field_add:skyproto.mohair.CpuSpec.cache_sizes)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& CpuSpec::cache_sizes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skyproto.mohair.CpuSpec.cache_sizes)
  return _internal_cache_sizes();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* CpuSpec::mutable_cache_sizes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skyproto.mohair.CpuSpec.cache_sizes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cache_sizes();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
CpuSpec::_internal_cache_sizes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cache_sizes_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* CpuSpec::_internal_mutable_cache_sizes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cache_sizes_;
}

// optional uint32 count_threads = 3 [json_name = "countThreads"];
inline bool CpuSpec::has_count_threads() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CpuSpec::clear_count_threads() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_threads_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t CpuSpec::count_threads() const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.CpuSpec.count_threads)
  return _internal_count_threads();
}
inline void CpuSpec::set_count_threads(::uint32_t value) {
  _internal_set_count_threads(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:skyproto.mohair.CpuSpec.count_threads)
}
inline ::uint32_t CpuSpec::_internal_count_threads() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_threads_;
}
inline void CpuSpec::_internal_set_count_threads(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_threads_ = value;
}

// -------------------------------------------------------------------

// MemorySpec

// uint32 count_mebibytes = 1 [json_name = "countMebibytes"];
inline void MemorySpec::clear_count_mebibytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_mebibytes_ = 0u;
}
inline ::uint32_t MemorySpec::count_mebibytes() const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.MemorySpec.count_mebibytes)
  return _internal_count_mebibytes();
}
inline void MemorySpec::set_count_mebibytes(::uint32_t value) {
  _internal_set_count_mebibytes(value);
  // @@protoc_insertion_point(field_set:skyproto.mohair.MemorySpec.count_mebibytes)
}
inline ::uint32_t MemorySpec::_internal_count_mebibytes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_mebibytes_;
}
inline void MemorySpec::_internal_set_count_mebibytes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_mebibytes_ = value;
}

// optional .skyproto.mohair.MemorySpec.MemoryType memory_type = 2 [json_name = "memoryType"];
inline bool MemorySpec::has_memory_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void MemorySpec::clear_memory_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memory_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::skyproto::mohair::MemorySpec_MemoryType MemorySpec::memory_type() const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.MemorySpec.memory_type)
  return _internal_memory_type();
}
inline void MemorySpec::set_memory_type(::skyproto::mohair::MemorySpec_MemoryType value) {
  _internal_set_memory_type(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:skyproto.mohair.MemorySpec.memory_type)
}
inline ::skyproto::mohair::MemorySpec_MemoryType MemorySpec::_internal_memory_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::skyproto::mohair::MemorySpec_MemoryType>(_impl_.memory_type_);
}
inline void MemorySpec::_internal_set_memory_type(::skyproto::mohair::MemorySpec_MemoryType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memory_type_ = value;
}

// optional uint32 memory_freq = 3 [json_name = "memoryFreq"];
inline bool MemorySpec::has_memory_freq() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void MemorySpec::clear_memory_freq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memory_freq_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t MemorySpec::memory_freq() const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.MemorySpec.memory_freq)
  return _internal_memory_freq();
}
inline void MemorySpec::set_memory_freq(::uint32_t value) {
  _internal_set_memory_freq(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:skyproto.mohair.MemorySpec.memory_freq)
}
inline ::uint32_t MemorySpec::_internal_memory_freq() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.memory_freq_;
}
inline void MemorySpec::_internal_set_memory_freq(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memory_freq_ = value;
}

// optional uint32 count_channels = 4 [json_name = "countChannels"];
inline bool MemorySpec::has_count_channels() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void MemorySpec::clear_count_channels() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_channels_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t MemorySpec::count_channels() const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.MemorySpec.count_channels)
  return _internal_count_channels();
}
inline void MemorySpec::set_count_channels(::uint32_t value) {
  _internal_set_count_channels(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:skyproto.mohair.MemorySpec.count_channels)
}
inline ::uint32_t MemorySpec::_internal_count_channels() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_channels_;
}
inline void MemorySpec::_internal_set_count_channels(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_channels_ = value;
}

// -------------------------------------------------------------------

// PlatformSpec

// repeated .skyproto.mohair.CpuSpec cpu_info = 1 [json_name = "cpuInfo"];
inline int PlatformSpec::_internal_cpu_info_size() const {
  return _internal_cpu_info().size();
}
inline int PlatformSpec::cpu_info_size() const {
  return _internal_cpu_info_size();
}
inline void PlatformSpec::clear_cpu_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_info_.Clear();
}
inline ::skyproto::mohair::CpuSpec* PlatformSpec::mutable_cpu_info(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:skyproto.mohair.PlatformSpec.cpu_info)
  return _internal_mutable_cpu_info()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::skyproto::mohair::CpuSpec>* PlatformSpec::mutable_cpu_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skyproto.mohair.PlatformSpec.cpu_info)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cpu_info();
}
inline const ::skyproto::mohair::CpuSpec& PlatformSpec::cpu_info(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skyproto.mohair.PlatformSpec.cpu_info)
  return _internal_cpu_info().Get(index);
}
inline ::skyproto::mohair::CpuSpec* PlatformSpec::add_cpu_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::skyproto::mohair::CpuSpec* _add = _internal_mutable_cpu_info()->Add();
  // @@protoc_insertion_point(field_add:skyproto.mohair.PlatformSpec.cpu_info)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::CpuSpec>& PlatformSpec::cpu_info() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skyproto.mohair.PlatformSpec.cpu_info)
  return _internal_cpu_info();
}
inline const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::CpuSpec>&
PlatformSpec::_internal_cpu_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpu_info_;
}
inline ::google::protobuf::RepeatedPtrField<::skyproto::mohair::CpuSpec>*
PlatformSpec::_internal_mutable_cpu_info() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cpu_info_;
}

// repeated .skyproto.mohair.MemorySpec mem_info = 2 [json_name = "memInfo"];
inline int PlatformSpec::_internal_mem_info_size() const {
  return _internal_mem_info().size();
}
inline int PlatformSpec::mem_info_size() const {
  return _internal_mem_info_size();
}
inline void PlatformSpec::clear_mem_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mem_info_.Clear();
}
inline ::skyproto::mohair::MemorySpec* PlatformSpec::mutable_mem_info(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:skyproto.mohair.PlatformSpec.mem_info)
  return _internal_mutable_mem_info()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::skyproto::mohair::MemorySpec>* PlatformSpec::mutable_mem_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skyproto.mohair.PlatformSpec.mem_info)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_mem_info();
}
inline const ::skyproto::mohair::MemorySpec& PlatformSpec::mem_info(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skyproto.mohair.PlatformSpec.mem_info)
  return _internal_mem_info().Get(index);
}
inline ::skyproto::mohair::MemorySpec* PlatformSpec::add_mem_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::skyproto::mohair::MemorySpec* _add = _internal_mutable_mem_info()->Add();
  // @@protoc_insertion_point(field_add:skyproto.mohair.PlatformSpec.mem_info)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::MemorySpec>& PlatformSpec::mem_info() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skyproto.mohair.PlatformSpec.mem_info)
  return _internal_mem_info();
}
inline const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::MemorySpec>&
PlatformSpec::_internal_mem_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mem_info_;
}
inline ::google::protobuf::RepeatedPtrField<::skyproto::mohair::MemorySpec>*
PlatformSpec::_internal_mutable_mem_info() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.mem_info_;
}

// -------------------------------------------------------------------

// ServiceConfig

// bool is_active = 1 [json_name = "isActive"];
inline void ServiceConfig::clear_is_active() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_active_ = false;
}
inline bool ServiceConfig::is_active() const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.ServiceConfig.is_active)
  return _internal_is_active();
}
inline void ServiceConfig::set_is_active(bool value) {
  _internal_set_is_active(value);
  // @@protoc_insertion_point(field_set:skyproto.mohair.ServiceConfig.is_active)
}
inline bool ServiceConfig::_internal_is_active() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_active_;
}
inline void ServiceConfig::_internal_set_is_active(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_active_ = value;
}

// string label = 2 [json_name = "label"];
inline void ServiceConfig::clear_label() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.label_.ClearToEmpty();
}
inline const std::string& ServiceConfig::label() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skyproto.mohair.ServiceConfig.label)
  return _internal_label();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ServiceConfig::set_label(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.label_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:skyproto.mohair.ServiceConfig.label)
}
inline std::string* ServiceConfig::mutable_label() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:skyproto.mohair.ServiceConfig.label)
  return _s;
}
inline const std::string& ServiceConfig::_internal_label() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.label_.Get();
}
inline void ServiceConfig::_internal_set_label(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.label_.Set(value, GetArena());
}
inline std::string* ServiceConfig::_internal_mutable_label() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.label_.Mutable( GetArena());
}
inline std::string* ServiceConfig::release_label() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:skyproto.mohair.ServiceConfig.label)
  return _impl_.label_.Release();
}
inline void ServiceConfig::set_allocated_label(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.label_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.label_.IsDefault()) {
    _impl_.label_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:skyproto.mohair.ServiceConfig.label)
}

// string location = 3 [json_name = "location"];
inline void ServiceConfig::clear_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.location_.ClearToEmpty();
}
inline const std::string& ServiceConfig::location() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skyproto.mohair.ServiceConfig.location)
  return _internal_location();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ServiceConfig::set_location(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.location_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:skyproto.mohair.ServiceConfig.location)
}
inline std::string* ServiceConfig::mutable_location() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:skyproto.mohair.ServiceConfig.location)
  return _s;
}
inline const std::string& ServiceConfig::_internal_location() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.location_.Get();
}
inline void ServiceConfig::_internal_set_location(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.location_.Set(value, GetArena());
}
inline std::string* ServiceConfig::_internal_mutable_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.location_.Mutable( GetArena());
}
inline std::string* ServiceConfig::release_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:skyproto.mohair.ServiceConfig.location)
  return _impl_.location_.Release();
}
inline void ServiceConfig::set_allocated_location(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.location_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.location_.IsDefault()) {
    _impl_.location_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:skyproto.mohair.ServiceConfig.location)
}

// optional .skyproto.mohair.DecomposeAlg decompose_alg = 4 [json_name = "decomposeAlg"];
inline bool ServiceConfig::has_decompose_alg() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ServiceConfig::clear_decompose_alg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.decompose_alg_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::skyproto::mohair::DecomposeAlg ServiceConfig::decompose_alg() const {
  // @@protoc_insertion_point(field_get:skyproto.mohair.ServiceConfig.decompose_alg)
  return _internal_decompose_alg();
}
inline void ServiceConfig::set_decompose_alg(::skyproto::mohair::DecomposeAlg value) {
  _internal_set_decompose_alg(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:skyproto.mohair.ServiceConfig.decompose_alg)
}
inline ::skyproto::mohair::DecomposeAlg ServiceConfig::_internal_decompose_alg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::skyproto::mohair::DecomposeAlg>(_impl_.decompose_alg_);
}
inline void ServiceConfig::_internal_set_decompose_alg(::skyproto::mohair::DecomposeAlg value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.decompose_alg_ = value;
}

// optional .skyproto.mohair.PlatformSpec service_platform = 5 [json_name = "servicePlatform"];
inline bool ServiceConfig::has_service_platform() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.service_platform_ != nullptr);
  return value;
}
inline void ServiceConfig::clear_service_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.service_platform_ != nullptr) _impl_.service_platform_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::skyproto::mohair::PlatformSpec& ServiceConfig::_internal_service_platform() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::skyproto::mohair::PlatformSpec* p = _impl_.service_platform_;
  return p != nullptr ? *p : reinterpret_cast<const ::skyproto::mohair::PlatformSpec&>(::skyproto::mohair::_PlatformSpec_default_instance_);
}
inline const ::skyproto::mohair::PlatformSpec& ServiceConfig::service_platform() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skyproto.mohair.ServiceConfig.service_platform)
  return _internal_service_platform();
}
inline void ServiceConfig::unsafe_arena_set_allocated_service_platform(::skyproto::mohair::PlatformSpec* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.service_platform_);
  }
  _impl_.service_platform_ = reinterpret_cast<::skyproto::mohair::PlatformSpec*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:skyproto.mohair.ServiceConfig.service_platform)
}
inline ::skyproto::mohair::PlatformSpec* ServiceConfig::release_service_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::skyproto::mohair::PlatformSpec* released = _impl_.service_platform_;
  _impl_.service_platform_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::skyproto::mohair::PlatformSpec* ServiceConfig::unsafe_arena_release_service_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:skyproto.mohair.ServiceConfig.service_platform)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::skyproto::mohair::PlatformSpec* temp = _impl_.service_platform_;
  _impl_.service_platform_ = nullptr;
  return temp;
}
inline ::skyproto::mohair::PlatformSpec* ServiceConfig::_internal_mutable_service_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.service_platform_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::skyproto::mohair::PlatformSpec>(GetArena());
    _impl_.service_platform_ = reinterpret_cast<::skyproto::mohair::PlatformSpec*>(p);
  }
  return _impl_.service_platform_;
}
inline ::skyproto::mohair::PlatformSpec* ServiceConfig::mutable_service_platform() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::skyproto::mohair::PlatformSpec* _msg = _internal_mutable_service_platform();
  // @@protoc_insertion_point(field_mutable:skyproto.mohair.ServiceConfig.service_platform)
  return _msg;
}
inline void ServiceConfig::set_allocated_service_platform(::skyproto::mohair::PlatformSpec* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.service_platform_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.service_platform_ = reinterpret_cast<::skyproto::mohair::PlatformSpec*>(value);
  // @@protoc_insertion_point(field_set_allocated:skyproto.mohair.ServiceConfig.service_platform)
}

// repeated .skyproto.mohair.ServiceConfig downstream = 6 [json_name = "downstream"];
inline int ServiceConfig::_internal_downstream_size() const {
  return _internal_downstream().size();
}
inline int ServiceConfig::downstream_size() const {
  return _internal_downstream_size();
}
inline void ServiceConfig::clear_downstream() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.downstream_.Clear();
}
inline ::skyproto::mohair::ServiceConfig* ServiceConfig::mutable_downstream(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:skyproto.mohair.ServiceConfig.downstream)
  return _internal_mutable_downstream()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::skyproto::mohair::ServiceConfig>* ServiceConfig::mutable_downstream()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:skyproto.mohair.ServiceConfig.downstream)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_downstream();
}
inline const ::skyproto::mohair::ServiceConfig& ServiceConfig::downstream(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:skyproto.mohair.ServiceConfig.downstream)
  return _internal_downstream().Get(index);
}
inline ::skyproto::mohair::ServiceConfig* ServiceConfig::add_downstream() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::skyproto::mohair::ServiceConfig* _add = _internal_mutable_downstream()->Add();
  // @@protoc_insertion_point(field_add:skyproto.mohair.ServiceConfig.downstream)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::ServiceConfig>& ServiceConfig::downstream() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:skyproto.mohair.ServiceConfig.downstream)
  return _internal_downstream();
}
inline const ::google::protobuf::RepeatedPtrField<::skyproto::mohair::ServiceConfig>&
ServiceConfig::_internal_downstream() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.downstream_;
}
inline ::google::protobuf::RepeatedPtrField<::skyproto::mohair::ServiceConfig>*
ServiceConfig::_internal_mutable_downstream() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.downstream_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace mohair
}  // namespace skyproto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::skyproto::mohair::CpuSpec_DeviceClass> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::skyproto::mohair::CpuSpec_DeviceClass>() {
  return ::skyproto::mohair::CpuSpec_DeviceClass_descriptor();
}
template <>
struct is_proto_enum<::skyproto::mohair::MemorySpec_MemoryType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::skyproto::mohair::MemorySpec_MemoryType>() {
  return ::skyproto::mohair::MemorySpec_MemoryType_descriptor();
}
template <>
struct is_proto_enum<::skyproto::mohair::DecomposeAlg> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::skyproto::mohair::DecomposeAlg>() {
  return ::skyproto::mohair::DecomposeAlg_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // skyproto_2fmohair_2ftopology_2eproto_2epb_2eh
